### ISSUE TITLE
Checklist before redeploy

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#1057]
I want to be sure everything is included before a redeploy. @MollieCourtenay can you go through and check this is what's needed for right now, then I can get it merged then deployed & hopefully James can test before end of day

- [x] Resize tick boxes #900 I couldn't get rid of the extra space under the box right now 😢 . There's extra space underneath it which I haven't found where it's coming from, but I thought it better to get the resized boxes in for now.
- [x] Sleep tracker hours change (for no data or 0 hours entered) #830 
- [x] Rearrange care plan details #42 
- [x] Add links to bottom of care plan for users with/without care plan https://github.com/healthlocker/healthlocker/issues/42#issuecomment-326562902
- [x] Add grey dividers to care plan between each main section #42 
- [x] Add link to coping strategies & goals in care plan #42

**Comment by MollieCourtenay** [comment]
looks good to me! thanks @katbow

**Comment by katbow** [comment]
Awesome, Simon is checking over the PRs now, so as soon as they're good & merged I'll redeploy!
