### ISSUE TITLE
Server Stuff

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#1158]
- [ ] Can't ssh into HL Staging server
Solved - wrong IP address being used... see #1159 for details.

 - [ ] Can only ssh into HL Live server 50% of time
Matt is going to do further investigation... He is going to get a diagnostic from the load balancer - he has done some checks and confirmed it is not the firewall or service itself.

- [ ] Restart Oxleas Live Server to test if the restart script works
Awaiting confirmation from SLaM that they are happy for us to go ahead.

- [ ] Implement/ Test restart script on HL staging (then leave client to test/ approve before implementing on live site) #1148 

- [x] More info on high CPU usage across ALL 4 Servers https://github.com/healthlocker/oxleas-adhd/issues/281
- [x] Why did Oxleas live server become unresponsive?  Did this happen to any other servers (e.g. Oxleas test which already had a restart script?!) #1156 
No concern on either point from SLaM - will move CPU issue to backlog to follow up in the future and keep an eye on it.

**Comment by katyedwards** [comment]
Notes added to original post ^^^
