### ISSUE TITLE
Sign up requirements

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#12]
As a person using HL,
I want to be able to sign up with my name (optional), email address,  password,  security question and answer, so that my account is protected**
There should be a form I can fill out to input this information, and when I complete this my information is saved so I can login at a later time.

# Acceptance Criteria (copy changes)

+ [x]  Replace 'Submit' with 'Next' on steps 1 and 2.
+ [x]  Replace 'Submit' with 'Create account' on step 3 (T&Cs).
+ [x]  Replace 'Repeat password' with 'Confirm password'
+ [ ]  I accept the terms of service (add 'the') **(remove full stop)**
+ [ ]  I accept the terms of the privacy statement (replace our with 'the') **(currently said s tatement)**
+ [x]  Replace anonymous data point with this copy 'I agree to my anonymous Healthlocker usage data being used by the Healthlocker team to improve the service and for researchers to use to drive forward the future of health care.'

# Wireframes
https://cloud.githubusercontent.com/assets/3858131/22781960/d6c14976-eebc-11e6-8344-bdc950ef8be8.png

# Tasks

- [x] Generate user model in phoenix
- [x] Add more fields to user model for sign up (less were included in login only) -> see #86 
- [x] Create multistep form which saves data at each step
- [x] Set default role to one with basic permissions - can deal with how to update roles/permissions for clinicians after ePJS.
- [x] Include new route for adding a new user
- [x] Style sign up form

**Comment by nelsonic** [comment]
@katbow this story has _enough_ detail for us to _start_ work.
_Ideally_ we would have some **_acceptance_ criteria** and prioritisation done by @MollieCourtenay before we estimate it...
But given that we _know_ that Authentication will be a _requirement_ regardless of the process/fields because we want to _protect_ the end-user's info, we can do _some_ work already...

If you are feeling bettererer this morning and want to start pairing on this, let me know. thanks! 👍

**Comment by katbow** [comment]
@nelsonic sounds like a good thing to start on 👍 . I am feeling better so we can get started! 🎉

**Comment by nelsonic** [comment]
@katbow are you coming to `#14`, `#16` or @DWYLHQ or WFH? 🤔

**Comment by katbow** [comment]
@nelsonic I'm currently upstairs in 14

**Comment by LauraNevo** [comment]
- On the UX side, we feel the flow requires way too many steps (12 fields in 2 pages + terms & conditions).
- We know some people had trouble with the current online version of MyHealthlocker (not created by us) and clinicians sometimes have to help with people forgetting their password, reset, etc...
- Not sure what's the minimum or unique information that can be used to identify an end user
- Not sure what information is *actually* secure (name, date of birth are easy to find, PINs are forgettable and not actually secure)
- NHS number is hard to find / know, end user may not have it on them when subscribing to HL.

### The old version:
![login](https://cloud.githubusercontent.com/assets/3858131/22341561/286973ea-e3e9-11e6-8192-576074fa4b74.png)


### What I think it should look like:
(possibly with optional phone number for recovery)
![loginmvp](https://cloud.githubusercontent.com/assets/3858131/22341579/4042b62a-e3e9-11e6-8e26-008f6e910f68.png)

**Comment by nelsonic** [comment]
@LauraNevo thanks for uploading the UX Wireframes. 😍

**Comment by MollieCourtenay** [comment]
@nelsonic @lauranevo @katbow 
I am back on Healthlocker today and plan to spend a big chunk of time on GitHub. 
The sign up needs some thought. 
- we want people to sign up as easily as possible whilst keeping in mind slam service users will benefit if they autheicate themselves / connect their HL account to SLaMs clinical record. So if this is not part of sign up - it needs to be something the user is reminded of and prompted to do post sign up and likely subsequent log-ins. 

- So on sign-up we could ask for name (optional) email, password and then ask them to tick if they are a service user at SLaM. Which we can use to prompt later on. 

- C4C will no longer be part of the sign up experience. 

Laura and I have not discussed the wires for the simple sign up but we will some more today.

**Comment by katbow** [comment]
Thanks @LauraNevo for the wireframes & @MollieCourtenay for the info about the sign up experience!

**Comment by MollieCourtenay** [comment]
@LauraNevo and I discussed this Friday, she can get wires to you Monday first thing for the 'simple sign-up'.

**Comment by LauraNevo** [comment]
![sign up - simple](https://cloud.githubusercontent.com/assets/3858131/22424950/ce57d382-e6f0-11e6-9b9d-d95b14928590.png)

**Comment by katbow** [comment]
@LauraNevo thanks for those! Looks great 👍

**Comment by LauraNevo** [comment]
Quick update to the wireframes above to include confirm password fields following #28 
![sign up - simple](https://cloud.githubusercontent.com/assets/3858131/22781960/d6c14976-eebc-11e6-8344-bdc950ef8be8.png)

**Comment by katbow** [comment]
@LauraNevo @MollieCourtenay @katyedwards 

What are your thoughts on having the terms & conditions/privacy/data access shown as links on page2, then users submit from there? Also, I believe @pm5k mentioned on another issue that one concern with having users repeat the password is that they may enter it incorrectly twice (I know I've done this before!) It also lengthens the signup process by having another field to fill in. 

Instead the password could be displayed, as was originally suggested, if the user clicks to do this. It would allow the user to see if they have written as they intended for certain, and saves having another field (and possibly another separate page for T&Cs).

![image](https://cloud.githubusercontent.com/assets/1287388/22792153/bc4bed18-eee3-11e6-9f37-3fc5db27a984.png)

**Comment by katyedwards** [comment]
@katbow Not sure to be honest, that'll be a question for @MollieCourtenay tomorrow, sorry!

**Comment by MollieCourtenay** [comment]
@katbow the T&Cs section is likely to contain much more text (closer to what is in the wireframe) than what you have there. Thats why it was designed to be on its own page. 

The idea is to make it feel simple for users, if we can achieve a good experience with 2 pages that would be great.
 
The T&Cs are being drafted at the moment by the IG team at SLaM as I mentioned Tuesday.

**Comment by katbow** [comment]
The part I have there isn't meant to be the full T&Cs - it's a link which would go to a separate page containing the complete terms and conditions. So it would still be it's own page, however it isn't part of the signup flow unless the user *wants* it to be, similar to [skype](https://signup.live.com/signup?lcid=1033&wa=wsignin1.0&rpsnv=13&ct=1486722107&rver=6.6.6577.0&wp=MBI_SSL&wreply=https%3a%2f%2flw.skype.com%2flogin%2foauth%2fproxy%3fclient_id%3d578134%26redirect_uri%3dhttps%253A%252F%252Fweb.skype.com%26site_name%3dlw.skype.com%26form%3dmicrosoft_registration%26fl%3dphone2&lc=1033&id=293290&mkt=en-GB&uaid=c5fb7bed04fc1b4f1c2b7b5e5782d491&psi=skype&lw=1&cobrandid=90010&client_flight=hsu%2cReservedFlight33%2cReservedFlight67&fl=phone2&lic=1) and [many other sites](https://termsfeed.com/blog/examples-i-agree-to/).

**Comment by MollieCourtenay** [comment]
@katbow yeah I understand that but we have agreed with Murat there will be a condensed mini-version visible to the user on sign up - as well as links to the full T&Cs on a new page.

**Comment by katbow** [comment]
Alright cool :+1:. Thanks for the clarification!

**Comment by katbow** [comment]
I'm putting together the last page today, but I'll just put in some generic text for now until there's the full version. It will be easy to pop that in at a later date :).

**Comment by katbow** [comment]
@MollieCourtenay I made these copy changes. The I kept it as terms of service instead of terms and conditions since that wording changed since this issue was added. Let me know if that's correct!

**Comment by MollieCourtenay** [comment]
@katbow a couple of small things in bold in the ACs.

terms of service - remove full stop
privacy statement - remove space

<img width="757" alt="screen shot 2017-03-27 at 08 54 29" src="https://cloud.githubusercontent.com/assets/25012688/24346137/06a9dff4-12cb-11e7-8906-7386c1fd965b.png">

**Comment by katbow** [comment]
Would you like it to say terms of service or terms and conditions still?

**Comment by MollieCourtenay** [comment]
terms of service please - just remove the dot.

we'll need to change footer to say terms of service. ill make a new issue.

**Comment by MollieCourtenay** [comment]
@katbow is this ready to test & close?

**Comment by katbow** [comment]
@MollieCourtenay yes it is 🙂
