### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#172]
As a user I can see the footer, which will provide me links to pages with necessary information.

## Acceptance criteria
+ [x] I can see a footer on every page
+ [x] Link to About page #23
+ [x] Link to page with T&Cs #157
+ [x] Link to page with Privacy Statement #173

**Comment by katbow** [comment]
@MollieCourtenay please verify this is for sprint 5 from our discussions yesterday

**Comment by MollieCourtenay** [comment]
looks good thanks
