### ISSUE TITLE
Account - epic

### ISSUE THREAD

**Issue by LauraNevo** [healthlocker/healthlocker#28]
I suspect this needs to be an epic as it's quite complicated. Not sure how to sort this out though.

![profile](https://cloud.githubusercontent.com/assets/3858131/22461760/7f2461d8-e7a2-11e6-95fe-78c2b96146f0.png)

These are the different important parts:
- Connect with SLaM
- See/view my profile details
-- SLaM user (+ update phone and address / clinician notified)
-- Non-SLaM user
- Update security details (password and security question) #127 
- Research and C4C consent

Can I get people's thoughts on this?

**Comment by MollieCourtenay** [comment]
Content for the C4C bit

**C4C**

If you are interested in taking part in research that contributes to better health for people with mental health related problems, you can sign up to a register called Consent for Contact (C4C).

When you join you'll give your consent for researchers to look at your SLaM record and see if you could be suitable for specific research projects. All researchers work for or are approved by South London and Maudsley NHS Foundation Trust (SLaM).

Find out more about C4C. (http://www.slam.nhs.uk/research/patient-involvement/current-opportunities/consent-for-contact)


[  ]  I want to register for C4C.
Your care team will be notified that you want to join the C4C register, if they believe you have the capacity to give consent they will add you to the register. You can discuss it with then when you next see them.

_____

NB: this is going to have to link to another issue once we have a clinician interface.

**Comment by MollieCourtenay** [comment]
I'm going run through the consent wording with Murat on Friday.

Am working in this google doc FYI. 
https://docs.google.com/document/d/1JoQwrAM-bUqEbxoteh3McCfZ5qo6ciSnUAu13ucihYI/edit

**Comment by MollieCourtenay** [comment]
## Acceptance Criteria 

PROFILE
+ [ ] As a user the details I entered during or since sign-up are displayed (definitely email, if Non-SLaM, may also show a name and phone number, if a SLaM connected user then first and last name, NHS number, DOB, email and maybe phone number and address) 
+ [ ] I can add / update my name (if not SLaM service user)
+ [ ] I can add / update my phone number, address and email address.
(Need to consider when developing clinician interface: if I am a SLaM service user this will notify my clinician who can choose to update that field in ePJS via an API if available if not manually.)
**Not sure about what the knock on effect that is with user’s HL account - do we validate somehow with a link?** @katbow @nelsonic 

+ [ ] As a user I can tick if I am a SLaM service user
+ [ ] If I have ticked that I am a SLaM service user, (just now or some other time in the past, a link to 'Connect with that service user’s SLaM care team' (?) is revealed below.
+ [ ] If I click on the (?) I am told how to connect, the benefits and reassured about sharing info.
+ [ ] If I click the link, a new page is loaded, I am asked to enter my First name, Last name and Date of Birth and NHS number (?).
+ [ ] If I click on the NHS number (?) I am told where to find an NHS number.
+ [ ] Once I have filled in all fields and click connect, the data is matched against records in epjs.
+ [ ] If the data matches, I have successfully connected my account.
+ [ ] If the data does not match, I see an error message and can try again.

NB: when it comes to carers family, friends and carers connecting to Clinicians - there will be a pretty similar journey as above - which is a HL project priority 3.

**Comment by MollieCourtenay** [comment]
## Acceptance Criteria 

CONSENT
+ [ ] As a user my current choice on whether I agree to share anonymous data is displayed in a tick box.
 + [ ] As a user I an tick or untick and ‘update’ my decision.


+ [ ] C4C section will ONLY be shown to users that have connected to SLaM and are over 18.
+ [ ] As a SLaM service user who is 18+, I can read about C4C on HL.
+ [ ] As a SLaM service user who is 18+, I can link out to more information on the SLaM website.
+ [ ] As a SLaM service user who is 18+, I can tick to express my interest in wanting to join the register and ‘update’ my decision.
+ [ ] As a SLaM service user who is 18+, I will know if I am on the C4C register.
+ [ ] As a SLaM service user who is 18+, I will be able to request to be removed from the C4C register.

**Comment by MollieCourtenay** [comment]
## Acceptance Criteria 

SECURITY

+[ ] as a user if I click on update my password, I am taken to a new page, asked to enter my current password and a new one.
@katbow @nelsonic  be good to get your thoughts on entering a new password twice? (being a dyslexic i believe that has saved me a couple of times haha!)
+[ ] When I have updated my password, I am assured it’s been updated, then am asked to log in with my new password.

+[ ] as a user if I click on update my security question, I am taken to a new page, asked to enter the answer to my current question. Then pick a new question, and enter a new answer. Then click update.
+[ ] When I have updated my password, I am assured it’s been updated.

**Comment by LauraNevo** [comment]
I'd also like to hear your thoughts about repeated password entry. I know it's a debate that comes regularly in online design communities. Have you heard about a definitive answer about this? What's your experience of it?

http://uxmovement.com/forms/why-the-confirm-password-field-must-die/
https://www.formulate.com.au/blog/double-entry-form-fields/

**Comment by pm5k** [comment]
So I kind of wanted to chip in regarding password updates here, @MollieCourtenay and @LauraNevo because this has come up before.

**Full disclosure:**
_I was previously against password confirmation fields (and outside the context of HL - still am)._

While it's true that having a confirm field would catch errors when comparing the two passwords, what happens in the instance (while rare, still..) that I mis-spell both in the same manner. So for example, I enter - **1337pws** instead of **1337pwd** twice. This effectively passes validation, yet is still incorrect.
Something to consider?

On top of which, can we be sure having the extra field won't frustrate people prone to mixing up passwords due to a pre-existing condition?

Written language analysis won't work here on pre-hashing and is useless to check for mis-typed passwords since they (should) have no linguistic meaning.

While a fine point, it will be quite hard to properly address dyslexic users since there is no set way they substitute characters when they write. Which means you can't really use any means of prediction/error correction effectively enough. It'd be pointless.

So in a perfect world, where users don't make mistakes and are responsible enough to admit when they do - instead of blaming the service, you would not have to have a confirm password field.
This ain't that world. So there's no need to make a big deal out of a single form field. I think it helps more having it inside HL than it hurts from a design stand-point.

**Comment by katbow** [comment]
@MollieCourtenay is there an issue for changing password or for changing security question/answer? I wasn't sure if I was missing it.

**Comment by iteles** [comment]
@katyedwards We've dealt with everything other than C4C on this because we still need further discussion here. Could we please open a separate issue on this and test the current issue?

**Comment by katyedwards** [comment]
@iteles the C4C stuff seems to already be split out into other issues - #60 #120 #129 so I think this can be closed now and we leave them as a separate topic.

The only other thing we're missing is #118 and the actual ePJS connection, but we have so many issues around that so I think we close this one now.

Does that sound right?

**Comment by katbow** [comment]
@katyedwards yes, definitely covered in #120 & #129 ! Thanks for linking those ones here

**Comment by katyedwards** [comment]
Thanks @katbow will close this one then and we'll carry on with the other C4C issues
