### ISSUE TITLE
For connected SLaM SUs: Make it clear that goals / CS / tracking are shared with care team.

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#305]
+ [x] As a SLaM connected SU, I see a static line of red text at the bottom of the Goals list page that says     'Your Care team will also be able to see your Goals.' https://www.healthlocker.uk/goal

+ [x] As a SLaM connected SU, I see a static line of red text at the bottom of the Coping strategy list page that says   'Your Care team will also be able to see your Coping strategies.' 
https://www.healthlocker.uk/coping-strategy

+ [x] As a SLaM connected SU, I see a static line of red text at the bottom of the Tracking overview page that says    'Your Care team will also be able to see your Tracking overview.'
https://www.healthlocker.uk/sleep-tracker

**Comment by MollieCourtenay** [comment]
@cleop my HL account is a connected Carer not a service user, so I should not be seeing this message. - Your Care team will also be able to see your tracking overview.

**Comment by Cleop** [comment]
Apologies @MollieCourtenay, I thought @katbow had made that change when she spotted it but it hasn't been made yet. It will get sorted tomorrow.
