### ISSUE TITLE
Tracking: Sleep tracker - input

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#320]
## Acceptance Criteria

+ [x] As a user, who has clicked on Sleep tracker in the Toolkit page,  I am taken to a page where I am invited to input data about my sleep.
+ [x] As a user, I must use a scroller to select how many hours sleep I got - the scroller begins at 0.5 hours and ends at 24 hours, and has .5 intervals.
+ [x] As a user, I can choose to use a scroller to enter how many times I woke up - the scroller shows these values: 0,1,2,3,4,5,6,7,8,9,10 and ends at 10+. 
+ [x] As a user, I can choose to add notes about my sleep.
+ [x] As a user I can click save as long as I have entered how many hours sleep I have had.

(no editing once saved)
(enter data only for this one occurrence, entering data for yesterday will be a new issue #322)

## Wording

##Sleep tracker
**Total hours sleep:**
[scroller]

**Times I woke up:**
[scroller]
 
**Notes:** 
_What affected your sleep? Did you have nightmares or terrors? Did you do something to try to get a  better sleep?_

![screen shot 2017-03-21 at 17 54 05](https://cloud.githubusercontent.com/assets/25012688/24162476/8ee4cb56-0e5f-11e7-81ff-b2b3609b0d3c.png)

**Comment by katbow** [comment]
@MollieCourtenay the scroller is the same type of input we're using for selecting security questions, correct?

**Comment by MollieCourtenay** [comment]
yes

**Comment by MollieCourtenay** [comment]
@katbow thanks!

+ [ ] Can the scrollers begin or default at 0? (this way the pages is less heavy with text)

+ [ ] increase the space between Sleep tracker & Total hours sleep:

+ [ ] can you try Sleep tracker in pink /red colour from style guide 

+ [ ] Save button, can this be an active colour - blue. (I know this is something that needs addressing throughout, but can we start here? Lets start with the button is always active.)



Ive made a separate card about making error messaging pink throughout HL. #360

**Comment by katbow** [comment]
> Can the scrollers begin or default at 0? (this way the pages is less heavy with text).

Do you want this to be a selectable option for people? It can be a placeholder where users can't select 0 (although that might be confusing).

**Comment by MollieCourtenay** [comment]
0 should be a selectable option yes please.

**Comment by MollieCourtenay** [comment]
Question...@katbow
So when a user inputs sleep data today (Tuesday), is their sleep data for Monday night? or Tuesday night? Tuesday night hasn't happened yet so should it be Monday night? It's just on the graph it filled in Tuesdays bar....

Is there something we should do in the FE to make it clear to the user what day they are entering information for? it could say ... **Total hours sleep last night:** ??

**Comment by iteles** [comment]
@MollieCourtenay My current fitness tracker (Bellabeat) displays Monday - Tuesday sleep data against Tuesday.

It would be good to know how fitbits and Jawbone fitness trackers display this too and find the most familiar user pattern to start from

**Comment by iteles** [comment]
@MollieCourtenay Just checked with a friend who has a Fitbit and last night's sleep was also recorded as Tuesday data.

**Comment by katbow** [comment]
@MollieCourtenay I marked this as please test despite the last 2 changes not being made since they are in separate issues #360 #363 and will be done site wide there
