### ISSUE TITLE
Tracking: overview (sleep data)

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#324]
As a user, I am able to review my tracking data that I have entered on a graph, so I can learn about myself.

## Acceptance Criteria

+ [x] As a user who has clicked on Tracking Overview in Toolkit, I am taken to the Tracking overview page.
+ [x] I see a bar graph, defaulted to show the last 7 days of my sleep data.
+ [x] underneath the graph, I can see my average hours sleep for the last 7 days.

+ [ ] I can choose for the graph to display by 'Last 7 days', 'Month' (calendar month), and '6 months' (last 6 calendar months) #382
+ [ ] As a user, I can choose the navigate with previous and next buttons, this will alter the graph and average data to show the previous or next 'Last 7 days', 'Month' or '6 months'. #383

<img width="276" alt="screen shot 2017-03-21 at 19 13 56" src="https://cloud.githubusercontent.com/assets/25012688/24166247/903f0844-0e6a-11e7-9945-091889ff8b27.png">

**Comment by katbow** [comment]
This answers my question for #323 I think. Tracking overview button goes to this page.

**Comment by LauraNevo** [comment]
Here is a screenshot with more data (+sleep tracker).
![tracking_day](https://cloud.githubusercontent.com/assets/3858131/24290651/a7b6266e-107d-11e7-9bc2-27ae8bc87fe4.png)

**Comment by katbow** [comment]
@LauraNevo so sleep should be in a bar graph instead of line graph?

**Comment by LauraNevo** [comment]
@katbow That's the idea at the moment:
- Mood = curve (up to 10)
- Sleep = bar (in hours)
- Exercise = bar (in hours)
- Weight = not sure but either also a curve, either simply the number in the report (Your day, your week, etc...)

Sleep and exercise both have a common unit, which is great. However, if we do end up letting the user report up to 15+ hours of sleeping, we're going to have bars that only fill half of the graph. Also, there's a question of how to compare sleep and exercise in a valuable way. Since it's my last day, it could be good to involve @indiamindwave24 as it'll be a big UI work to make these trackers understandable through visual elements.

**Comment by katbow** [comment]
@MollieCourtenay for this one:

> underneath the graph, I can see my average hours sleep for the last 7 days

is this always 7 days then? As in it doesn't show monthly average etc when you change the scale?

**Comment by katbow** [comment]
Also @MollieCourtenay can we start this with 7 days & Month views as options & wait for feedback on other time scales? There also won't be data to start with for longer time periods, so it won't be useful to view at first.

**Comment by katbow** [comment]
And one last question @MollieCourtenay , do you want any labels for the data underneath?

Something like...

**Today:** 7 hours sleep
**Week average:** 10.02 (is that what this number is?)
**Times awake:** 4 (not sure if this is supposed to be the average times awoken over 7 days or for just the current day?)
**Notes:** *notes about my sleep (from today only?)

Or is the average only in the section under "Your week"?

I'm slightly confused by what is what in the wireframe 😕

**Comment by MollieCourtenay** [comment]
@katbow the 10.02 is the timestamp that data was saved for that day. I don't think we need timestamps however in that view.

I have edited and re-added the screenshot above.

So:
**Last 7 days** - show averages.
**Today** - show just info entered about that day.

**Comment by MollieCourtenay** [comment]
If we can go last 7 days AND one month that would be great  - we can see how people are using the switching between 7 days and one month and see if a further timescale would be useful.

We do know form users they want to see their data over time.

**Comment by katbow** [comment]
@MollieCourtenay, I'm going to split these last 2 into separate issues for timing purposes. There was a bit more that had to go into this technically than I first anticipated, so it will be better for time estimating for me to split it up 👍

**Comment by MollieCourtenay** [comment]
@katbow please can you display the averages at the bottom like this: 

## 7 day average 
*Sleep* 7h 30m

**Comment by MollieCourtenay** [comment]
@katbow the graph is too big, Ive tried on a few desktop/laptops last week and end up having to zoom out in order to see the full graph. Can it be shrunk and therefore visible within the browser window without having to be shrunk down?

These are on my macbook, chrome.
<img width="1275" alt="screen shot 2017-04-14 at 08 37 20" src="https://cloud.githubusercontent.com/assets/25012688/25036788/ab680982-20ed-11e7-8bfd-4fd4fa8e9b7c.png">
<img width="1279" alt="screen shot 2017-04-14 at 08 37 46" src="https://cloud.githubusercontent.com/assets/25012688/25036791/acbad08a-20ed-11e7-82de-51ca5d268f94.png">


+ [ ] shrink graph /  make more responsive to larger screen sizes.

**Comment by katbow** [comment]
@MollieCourtenay we have the last 2 items split into separate issues now, so this is good for testing & closing for the first 3 items 👍
