### ISSUE TITLE
App Usage Data Logging and Analysis to Derive Actionable Insight

### ISSUE THREAD

**Issue by nelsonic** [healthlocker/healthlocker#35]
# Logging Usage Data/Stats to Get _Insights_

Logging and displaying usage data and corresponding insights ***to*** the people _using_ the application is vital to helping them understand their _own_ behaviour/patterns.

This is an `"Epic"` because it is **not a single story/task** but rather an **_on-going_ sub-project**. 

## (_User_) Stories

There are ***two*** "_user stories_" we need to _satisfy_ with our usage data logging effort:

> As an **person using the app** 
> I want to track my usage of the application 
> so that I know how often I interact with the app and how many useful articles/tips I have read.

> As a **product owner**, **stakeholder** or **member of the project/development team**
> I want to see the **usage statistics** for the various features of the application 
> **so that** I know if which features are being used/ignored and where to invest further resource.

## Initial Requirements

Our initial requirements are simply to start _logging_ the data. It does not need to be "_fancy/pretty_" but it does need to be ***reliable***. 

### Data to be Logged & Expected insight:

+ [ ] what **time** did I access the app? (_what time of day do I like using the app_?)
+ [ ] am I viewing the app/content **anonymously or logged in**?
+ [ ] what **device/browser** did I use the app on? (_so I know which is my preferred device_)
+ [ ] what are the **viewport dimensions** (_screen size_) in **pixels**?
+ [ ] what did I **content** (articles/stories/tips/events) did I look at (_read_)?
+ [ ] **how _long_** did I spend reading in the app today?

**Comment by katyedwards** [comment]
@nelsonic Question from Murat - would users have the option to switch this off?

His thoughts:
If it is anonymised data about how many people used which features or how many people dropped out of something before submitting, there is no problem and the info could be stored within HL & the SLaM environment or with a 3rd party like google analytics.

But if the info will be identifyable to an individual and if it would include anything that could be considered 'health information' then we may need to give it more thought and at least need to give them the option to turn it off and not be tracked.

@MollieCourtenay anything to add that I have missed on this point?

**Comment by nelsonic** [comment]
@katyedwards answer for Murat: ***yes***! (_absolutely, an easy `On/Off` switch will be built-in_!) 
Also, if PO decide to _make_ it a "User Story" (_requirement_) we _could_ allow user to "***Disable History***".
But technically, users are already _always anonymous_ to us if they aren't logged in 
so they can use the app, read the content without sharing _anything_ with HL app.
And if the person choses to login they will be given a "Session ID" which allows them to view their own history/usage of the app but users are ***Always*** in control of allowing _other people_ see their content/activity/data.

The _issue_ with attempting to anonymise data being sent to a 3rd party tool is that _unless_ we disable tracking on any "Personal" pages (_when the person is editing their personal details_)
the analytics script would be tracking the _entire_ session the person has in the app. 
This means the Analytics tool knows _exactly_ who is logged in and what behaviour they have taken.
 
> Google _sells_ the "aggregate" data (_not an individual level_) collected from ***all*** the (_millions of_) sites that use Google Analytics to their "Premium Analytics" Customers. 
I have seen this "Google Insights" data when working in the _Travel Industry_... 
Google has _detailed_ stats on _exactly_ who buys what types of products in every sector, 
including how old they are, estimated income levels, number of family members, location, etc...

My idea/proposal was we would write a couple of **_basic_ functions** (_built into the HL app_) 
to help people (_users_) track their _own_ history using the app. And instead of sending the "_click stream_" to Google (_or another 3rd party Analytics service_) we would _keep_ all that data within "SLaM" and under the _control_ of the _user_.

**Comment by tonydaly** [comment]
#193 started a bunch of this. I've updated this list above to reflect what is currently tracked (but people should take a deeper look into Mixpanel). The main thing missing from that list is: "how long did I spend reading in the app today?"

Also, there is currently no way to switch this off per user.
