### ISSUE TITLE
Tracking overview: click on a day - reveal details

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#386]
## Acceptance Criteria
+ [x] As a user, viewing my tracking graph, first I see my [time period] average. 
+ [x] As a user, viewing my tracking graph, below the [time period] averages, the tracking detail for each day is listed. Beginning with the most recent day and following backwards (e.g. Wednesday, Tuesday, Monday). 
+ [x] As a user, I do not see days listed where no data was entered.
+ [x] As a user I see the detail like this:
## 7 day average

**Sleep** 7h 30m

### Monday 15th March
**Sleep** 7h
Woke up: X times
_My notes go here._

### Sunday
**Sleep** 6h
Woke up: X times
_My notes go here._

### Friday
**Sleep** 8h
Woke up: X times
_My notes go here._

etc

<img width="193" alt="screen shot 2017-03-28 at 13 35 09" src="https://cloud.githubusercontent.com/assets/25012688/24405253/190fd1fc-13bc-11e7-8a3f-aaab741f8f9f.png">

**Comment by katbow** [comment]
@MollieCourtenay I had some questions for this one regarding the UX.

I am concerned that users may not know to click on the graph to get more information about the day. A graph is not generally considered a navigation tool, it's a viewing tool.

Looking at other sleep tracking interfaces, extra information is accessed by clicking on a separate day button/link, or having a small section of info about each day underneath the graph overview.

Here's an example from fitbit:

![image](https://cloud.githubusercontent.com/assets/1287388/24810602/be839a1e-1bba-11e7-8335-29b6256d56d0.png)

**Comment by MollieCourtenay** [comment]
@katbow  sorry for the delay. Hmm.  Guess I was imagining the days to be links and to be styles as per all other links on the site. Is that not going to be the case?

**Comment by katbow** [comment]
They are not links at the moment. I would have to look in to how to create links in this case since the labels/overall chart are created using [chart js](http://www.chartjs.org/), so I can't just put a link in directly.

Even if we can easily make them links, my concern is with the UX for this. 
* The links will be very small and likely difficult to click. This is similar for the bar graph itself -
 each bar will be quite narrow on mobile.
* Although they will have the same styling as all other links, it may not be obvious they are links. It's an unexpected place to have links, so it could be mistaken for a label style and not clicked on.

**Comment by iteles** [comment]
A note here that on fitbit and a few other wearables, there is no second screen, you just scroll down and there is essentially a list of days with their data underneath them (image from the interwebs below):
![fitbit-sleep](https://static1.fitbit.com/simple.b-cssdisabled-jpg.hb1361546c08554fec7f39399e78ad300.pack?items=%2Fcontent%2Fassets%2Fapp2%2Fimages%2Fscreen-01-sleep-goals-trends.jpg)

**Comment by MollieCourtenay** [comment]
ok so it seems we will have to begin the detailing under the graph with 7 day average, then list the 7 days under the graph.

For now as there is only one tracker, we could list them with the data 'open', be good to consider the option in the future to click on a day to then reveal the tracker data (mood, weight, exercise, sleep) rather than have it all on screen.

so:

## 7 day average

**Sleep** 7h 30m

### Monday
**Sleep** 7h

### Tuesday
**Sleep** 6h

### Wednesday
**Sleep** 8h

**Comment by katbow** [comment]
@MollieCourtenay I have everything displaying underneath now (although not merged in yet so not on the main site), but had a couple more Qs to finalise it.

What order should they be displayed in? I currently have them reflecting the same way as the graph - it starts with most recent day at the top, and each previous day as you scroll down. Is that correct?

Dates with no data are not being shown - I had them in at first, but it was just adding extra text without extra value. It would say *Tuesday* then go immediately to the next day if we do show day without data.

Can you update the acceptance criteria to reflect the changes we discussed & for the above questions?

**Comment by MollieCourtenay** [comment]
@katbow  done

**Comment by katbow** [comment]
@MollieCourtenay Is only the first day meant to have the date? Wasn't sure if it was meant to be on the other ones as well and was missed. Other than that this is complete 😃 .

**Comment by MollieCourtenay** [comment]
@katbow 
 + [ ] 7 day average is meant to be bigger, like a heading, sorry if that wasn't explicit above.

+ [ ] please add a line space (so there is double space) between the 7 day average section and where the daily details are listed.

+ [ ] they were meant to have the dates for each of the 7 days, yes please, sorry. (big job?)

**Comment by MollieCourtenay** [comment]
@katbow thanks! 

+ [ ] please add a divider between 7 day average and the first date with detail, (the extra spacing doesn't seem to have made enough difference.)

**Comment by katbow** [comment]
@indiamindwave24 how should this divider look?

**Comment by katyedwards** [comment]
@indiamindwave24 wasn't sure if you had seen this one as it had a question tag rather than a please test!

**Comment by katbow** [comment]
heh yeah it's a question.

**Comment by indiamindwave24** [comment]
Sorry for closing this prematurely — Please use the grey divider used between tip categories
