### ISSUE TITLE
Tracking - mood - input

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#435]
As a user I can enter how I am feeling multiple times a day, so that I am able to keep a record of my thoughts & emotions that know I can look back over it in the future - or discuss with my care team (if i have one).

## Acceptance criteria

+ [ ] As a user on Mood tracker, I can input how i'm feeling any time (multiple times a day)
+ [ ] As a user, I use the slider or clicker to select a number between 0 and 10 on the scale.
+ [ ] As a user, I then select at least 1 word to associate with how I am feeling, I am able to add a new word by clicking on Add.
+ [ ] As a user, I am unable to click next (and see error messages), If i have not selected a number on the scale and at least 1 word. 
+ [ ] As a user who has clicked next sucessfully, I have the option to add a note about why I feel this way, then click save.

<img width="500" alt="screen shot 2017-04-14 at 10 02 45" src="https://cloud.githubusercontent.com/assets/25012688/25039029/90655dcc-20f9-11e7-95d4-02c9c252c95e.png">

#431

**Comment by MollieCourtenay** [comment]
## Content

How are you feeling?

0 My worst
10 My best

Anxious
Overwhelmed
Motivated
Calm
Confused
Excited
Angry
Hopeful
Quiet
Worried
Happy
Lonely
Tired
Loud
Aggressive
Low
Energised
Sad
Confused


Next
___

**Why do you think you feel like this?**

What have you noticed about you thoughts, reactions or behaviour?
_What could be influencing how you are feeling or what you are thinking about?_

[text box]

 Back / Save
