### ISSUE TITLE
Tracker - exercise - input

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#436]
As a user I can enter the exercise I have been doing, so that I am able to keep a record to look back on to help me learn about myself - or discuss with my care team (if I have one).

## Acceptance criteria

+ [ ] As a user on Exercise tracker, I can input exercise any time (multiple times a day)
+ [ ] As a user, I type in the type of exercise I did in the top box.
+ [ ] As a user, I then select, using the scroller, how long I did that exercise for.
+ [ ] As a user, I can click 'Add more', to enable me to add more than one exercise input for one day. (When click on add more, it could either - Save the entry and reload the page. OR - Drop down the input fields repeated below, then hit Save...???)

<img width="278" alt="screen shot 2017-04-14 at 10 33 41" src="https://cloud.githubusercontent.com/assets/25012688/25039946/617675f0-20fe-11e7-93c3-4d97ae6c6335.png">

#433  

### Exercise (centred)

**What have you done today?** (left aligned)
For example, walking, swimming, football, yoga, weights or dancing.  (not italic) (left aligned)

**How long for?**
scroller:
15m
30m
45m
1h
1h 30m
2h
2h 30m
3h
3h 30m
4h
4h 30m
5h 
5h 30m
6h
6h 30m
7h
7h 30m
8h 
8h +

Add more / Save
