### ISSUE TITLE
Tracker - weight - input

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#437]
As a user I can enter my weight, so that I am able to keep a record to look back on to help me learn about myself - or discuss with my care team (if I have one).

## Acceptance criteria

+ [ ] As a user on Weight tracker, I can input my weight only once per day (error as per sleep)
+ [ ] As a user, I type in my weight as EITHER kg or Stones and pounds.
+ [ ] As a user, if I enter in kg, the Stones and lbs is automatically populated - and visa versa  - so that I am unable to enter two conflicting inputs.

<img width="225" alt="screen shot 2017-04-14 at 10 33 51" src="https://cloud.githubusercontent.com/assets/25012688/25040126/73f27192-20ff-11e7-8f97-13f860bab8ee.png">

#432   

### Weight (centred)

**kg** 

**Stone**    **Pound (lb)**

Save
