### ISSUE TITLE
Tracker - custom - input

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#438]
As a user I can enter my weight, so that I am able to keep a record to look back on to help me learn about myself - or discuss with my care team (if I have one).

## Acceptance criteria

+ [ ] As a user on Custom tracker, I can submit ideas anytime and any number of times a day. 
+ [ ] As a user, I type in my ideas or suggestions in the free text box.
+ [ ] As a user, If I have sent an idea, I am shown a success flash message.
<img width="268" alt="screen shot 2017-04-14 at 10 34 08" src="https://cloud.githubusercontent.com/assets/25012688/25040264/22af4534-2100-11e7-80d1-a92c2da5c7b8.png">

#434 

### Tell us what you want! (centred)

**If you could create a personalised tracker, what would you want to track and how?**
 
Your ideas will help us decide how to develop the tracking feature.

[ text box ] 

Send
