### ISSUE TITLE
Home page redesign

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#465]
![home](https://cloud.githubusercontent.com/assets/25007700/25191964/49b1d12e-2529-11e7-80d0-700c7f0800a9.png)

- [x] I will send SVG files for each tip category (5 ways to wellbeing) - the content for these sections can be found on this googledoc https://docs.google.com/document/d/1wHQVJp6p3W2_6debDxn8BtbbHwVPQI717csrodYgSnM/edit

- [x] Each tip category will have an icon and a small icon on each tip (so that when in a list view, it is clear what category they lie in)

- [x] Please see the signup/login buttons have moved

- [x] Story image should sit centered with the bookmark icon left aligned

**Comment by katbow** [comment]
@indiamindwave24 

* confirming this is the homepage view?
* Under the description of the tip category, is that an example of a tip from that category? 
* Are the 5 ways to wellbeing also on the general tips page or just here? I saw in #441 that in each section (connect, BeActive, etc) that it had the info for that particular category only, but wasn't sure how this looked on that page with all tips listed.

**Comment by iteles** [comment]
This looks to me to involve new functionality and some sizeable changes.

@Cleop Let's split this out and time estimate it please!

**Comment by indiamindwave24** [comment]
@katbow 

- Yes this is homepage view
- Example tips are in the Googledoc linked previously
- The 5 ways to wellbeing are the hashtag categories - the icon in the corner of the tips will highlight which category each tip belongs when viewed on the general tips page. If all tips are listed there will be no description at the top (general tips view) - @MollieCourtenay can you confirm?
- Sign up and log in will still be in nav menu. The login button on the top toolbar will not appear on mobile. It would be great if login could change to logout when someone is logged in (desktop/tablet, not mobile)

**Comment by Cleop** [comment]
To summarise, based on the design above these are the total changes for the homepage redesign:

HOME
- Move login link to navbar and change it to a button
- Move sign up link and change it to a button
- Change size, spacing and color of 'Welcome to Healthlocker' text

- Add title, copy and link for 'Tips: 5 ways to wellbeing'
- Add category introductions and images x 5
- Add example tip x 5
- Create black page rules at the beginning and the end of the tips section

- Center 'Stories' title and resize
- Resize individual story title
- Size restrict 'stories' images and shape as a circle
- Add a bookmark icon to the left of 'stories' image
- Change 'see more stories' link to a button

- Remove old tips section at the bottom

**Comment by MollieCourtenay** [comment]
@Cleop  Thanks for doing this. Sorry for not pulling this together properly.

Change 'see more stories' link to a button is here #420 

Make hashtag of tips aqua not black, with underline like a link - should be done now as all links will be aqua coloured. #370 

Ive made a new issue for the header #466

**Comment by Cleop** [comment]
Thanks @MollieCourtenay for taking a look and for these extra issues.

I've updated the comment so it now covers the ones that have existing issues, so we can see the picture fully. 

From testing the live site I think that the words following the hashtags are now aqua and underlined but based on how they're generated the hashtags have not been affected by this styling change and so this still remains...

**Comment by MollieCourtenay** [comment]
@Cleop ah so you mean literally the '#' is still dark blue - i'm happy to leave that as it is for now.

**Comment by katyedwards** [comment]
Great - very happy and we can now edit styling as needed.
