### ISSUE TITLE
Users need to input content

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#5]
As a `person` _using_ HL (_All users will create content_)
I need an intuitive way to `create content`
so that I can `share interesting thoughts` and practical insights 
with people I care about.

There are _many_ UI Examples for content input: https://pttrns.com/?scid=19
I _favour_ using the Twitter UI as a _starting point_:

![image](https://cloud.githubusercontent.com/assets/194400/22115821/621eb916-de66-11e6-9df5-752468935162.png)

Because it's the _simplest_ and lowest friction.

# Tasks:

- [x] Create HTML skeleton for content input UI

- [x] Style the HTML using tachyons

**Comment by katbow** [comment]
- [ ] Create HTML skeleton for content input UI

- [ ] Style the HTML using tachyons

**Comment by MollieCourtenay** [comment]
looks good
