### ISSUE TITLE
Tracking: INPUT: custom symptom tracker

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#560]
As a user, I can type in a problem I experience, e.g. Paranoid thoughts, controlling my eating, then rate how much is affecting me on a scale 0 - 10.

### acceptance criteria
+ [x] As a user that has not yet named my problem, I can read what the problem tracker is, and be given some prompts for how I use it.
+ [x] As a user that has not yet named my problem, I can type in a problem I experience. And click save.

+ [x] As a user who has named my problem,  I can see it as the title of the page when I first save the name of my problem tracker and my tracker loads for the first time. The title should read:  **Problem tracker: [problem entered by the user]**
+ [x] As a user who has named my problem, I can see it as the title of the page whenever I click on the problem tracker icon.

+ [x] As a user who has named my problem, I can rate how much that symptom is effecting me each day on a scroller 0-10. 
+ [x] As a user, I can write notes, I am prompted by some questions. (Optional, this doesn't have to be filled in)
+ [x] As a user, I can save.
+ [x] As a user, I can enter data on my problem tracker only once per day. If I enter track in info again, I see an error message - ''You can only enter problem tracker once per day."

## copy: 
https://docs.google.com/document/d/1Mokt9fQm4OaWfhPIDz7y4VyVzrcwtsmD05bgpU6Ps68/edit

**Comment by MollieCourtenay** [comment]
+ [ ] please edit to say: effected you today: 
instead of affected you today.

**Comment by nelsonic** [comment]
@MollieCourtenay  not sure I _understand_ the context of the sentence if it's `effected` 🤔 
`affected` vs `effected`: http://www.diffen.com/difference/Affected_vs_Effected

**Comment by MollieCourtenay** [comment]
@nelsonic YIKES. I had conflicting advice on this. Thanks for highlighting.

The decision is to go with:
In Q -  *affected*
In scale,  *effect*

@RobStallion sorry please can you change back to *affected*.

Then I'm happy to close the issue.
