### ISSUE TITLE
Tracking: INPUT: daily diary

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#561]
As a user, I can enter a dairy entry each day.

+ [x] As a user, I can read an introduction to how a diary can be used.
+ [x] As a user, I see the diary icon, centred, between 'A diary can be used in lots of ways.' section and 'You may want to think about:' section.
+ [x] As a user, I can write a diary entry, I am prompted by some questions. 
+ [x] As a user, I can save.
+ [x] As a user, I see a success flash message  -  "Diary saved successfully!"
+ [x] As a user, I will be able to save just one entry per day. But if I click on diary again within that day - my current entry is held in the text box which I can add too, and save to overwrite.

https://docs.google.com/document/d/1ucJYsbZRfMTZ9X8WpnPnDya4ni8KeJ5nUCeWkv0jvGI/edit

**Comment by iteles** [comment]
@MollieCourtenay When we discussed this at the sprint planning session we had a quick discussion around the single/multiple entry a day question.
Our conclusion at the time (which we based our estimates on) was that this would only be required once a day, in line with our UX for the other trackers. We also debated whether we would need to add in an editing feature (although we didn't have time for this in the sprint).

**Comment by MollieCourtenay** [comment]
@iteles I thought that conversation was about the symptom tracker due to the fiddlness of displaying multiple points on the graph. 
As we are not graphing the diary I had assumed this was less of a task. 

Would a user be able to save just one entry per day. But if they clicked on diary again within that day- their current entry is held in the text box which they can add too, and save to over write?

**Comment by RobStallion** [comment]
> Would a user be able to save just one entry per day. But if they clicked on diary again within that day- their current entry is held in the text box which they can add too, and save to over write?

@MollieCourtenay Have added this as you suggested instead of the multiple entries per day. Would you like to update this in the acceptance criteria?

**Comment by MollieCourtenay** [comment]
@RobStallion  getting internal server error here: https://www.healthlocker.uk/diary/new

**Comment by RobStallion** [comment]
Hey @MollieCourtenay. Sorry about the error there, fixed now.

**Comment by MollieCourtenay** [comment]
Hey @RobStallion I've tried to input on the Diary this morning via heroku link - https://healthlocker.herokuapp.com/diary

Once I saved - i got an internal server error.

**Comment by RobStallion** [comment]
hey @MollieCourtenay. Thanks for pointing that out. We changed the default limit @katbow mentioned in slack. You will more than likely get some errors the first few times that you go to the Diary, Problem tracker, Sleep tracker, Tracker overview and the goal pages but this should just be a caching issue. If you refresh a couple of time they should go away and never come back 👍

**Comment by MollieCourtenay** [comment]
@RobStallion  - I tried to put a link in to the diary entry and got internal server error.

**Comment by RobStallion** [comment]
@MollieCourtenay. I have just entered a url on the live site and it worked as expected. 

![image](https://cloud.githubusercontent.com/assets/15571853/26500754/0f0140b4-422f-11e7-9f9d-0125e5f85f92.png)

Could you check it again or show me what it is exactly that isn't working. Thanks

**Comment by MollieCourtenay** [comment]
good news is it is working fine for me too now! 
ill close the issue.
Maybe it was just waiting for that character limit thing to settle in :)
