### ISSUE TITLE
Throughout HL: replace Name (optional) with First Name, Last name fields

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#582]
+ [x] As a user when I sign up to HL, I am asked to add my First Name and Last name (this should replace the Name (optional) field.

+ [x] As a user in Account, I see a First name and Last name field (this should replace the Name (optional) field.

+ [x] As a user when I am connecting to SLaM as a service user, I must enter my First name and Last name.

+ [x] As a user when I am connecting to SLaM as a carer, I must enter my First name and Last name, as well as the First name and Last name of the service user.

+ [x] As a user, who has connect to SLaM as a carer / SU the First name and Last name that I enter when I connect overrides the First name and Last name that I entered on sign up.

**Comment by katbow** [comment]
@MollieCourtenay 2 questions for this:

1. Is the first & last name still optional on sign up?
1. Should name be editable still in account? Particularly for SLaM carer/SU? We can go the route we went with email and have it listed but as an uneditable field if we don't want them to change it.

**Comment by MollieCourtenay** [comment]
@katbow  
1. I'd say yes optional - what would you say?
2. First name and Last name should not be editable once connected to SLaM. IF not connected to SLaM can be editable.

**Comment by katbow** [comment]
Yep that sounds good to me. Thanks
