### ISSUE TITLE
Clinician UI

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#615]
# Clinician menu
<img width="858" alt="screen shot 2017-05-18 at 15 58 28" src="https://cloud.githubusercontent.com/assets/25012688/26208775/dfe7a432-3be2-11e7-97b0-3ca5519ab553.png">

+ [x] Grey background 

+ [x] Users name centred and bold e.g **Katherine Bowler** (Family, friend, carer) of **Evan Burns**  // or **Evan Burns**

+ [x] when a user clicks on a menu item, it goes pink and bold, and underlines in pink

# Clinician Goals and strategies
![clinician_goals_strategies](https://cloud.githubusercontent.com/assets/25012688/26208821/f6a3cd0e-3be2-11e7-92b4-7623fb556f15.png)

+ [x] add goals icon, centred in the column 
+ [x] add strategies icon, centred in the column 
+ [x] add dark blue separator line between goals and coping strategies
+ [x] add Goals centred title
+ [x] add Coping Strategies centred title
+ [x] add blue 30% opacity boxes for the goals
+ [x] add yellow 30% opacity boxes for the coping strategies
+ [x] right align the created stamp for coping strategies
+ [x] use regular not bold for coping strategies
+ [x] if possible, line break the coping strategies, if they have been input by the user with line breaks
+ [x] italicise 'Important' - same size as created text
+ [ ] add grey separator line at the end of live goals, achieved goals, and coping strategies
+ [ ] add Achieved goals centred title
+ [x] add dark blue trophy icon same size as the important star
+ [x] add right aligned Achieved time stamp, (do not include the colon from mock up)
+ [ ] list title and steps of achieved goals

# Clinician Tracking - 
![tracking view-01](https://cloud.githubusercontent.com/assets/25012688/26351387/5de35672-3faf-11e7-9f56-b1fb380a7718.png)
+ [x] 7 day average for Sleep = put in a blue 30% box
+ [x] each day put in a light grey box
+ [x] add the icon for each tracker that was completed for that day
+ [x] **Woke up** - make bold 
+ [x] add dark grey line separator between each tracker

![tracking_mobile](https://cloud.githubusercontent.com/assets/25012688/26242106/27546fb6-3c7f-11e7-9595-1aa07a92303d.png)

# Clinician Messaging
![clinician_messages](https://cloud.githubusercontent.com/assets/25012688/26208830/fdff5f8c-3be2-11e7-88c8-0257cd701cce.png)
+ [x] change the boxes to 30% opacity
+ [x] align the timestamp to the top of the box (not bottom) 
+ [x] change the timestamp to italic 
+ [x] timestamp in dark blue not white
+ [x] light grey thinner grey conversation outline box

# Clinician caseload 
![clinician_caseload](https://cloud.githubusercontent.com/assets/25012688/26207901/b8d4cba6-3be0-11e7-8180-8c956dee479b.png)
+ [x] make arrows pink
+ [x] only have arrows on Healthlocker users (remove from not signed up users)
+ [x] make Healthlocker service user boxes blue (30% opacity) 
+ [x] give Healthlocker carer boxes yellow outline
+ [x] **Service user full name** = bold . 
+ [x] **Carer full name** = bold . (family, friend, carer) in italics (like the Ines example not Katherine)
+ [x] Edit 'Inactive users' to 'Users not signed up to Healthlocker'
+ [x] Remove 'Users not signed up to Healthlocker' text next to each user name
+ [x] Change inactive username to half opacity
+ [x] reduce size of 'Healthlocker users' and 'Users not signed up to Healthlocker'
+ [x] add grey separator line between HL users and 'Users not signed up to Healthlocker'

# Clinician Details and contacts
![clinician_details](https://cloud.githubusercontent.com/assets/25012688/26208777/e4555b2c-3be2-11e7-8d98-29a4d9ac31e8.png)
+ [x] add yellow box at 30% opacity

__________

Nicola is reviewing and will make some suggestions.
Stephen wants it to look more like the first prototype  - **needs more colour and icons , less like a narrative, more hierarchy to the information.**

@indiamindwave24 can we have a chat about this next week?

**Comment by MollieCourtenay** [comment]
@Cleop can you take a look at the above and check the estimate - let me know if we need to split and prioritise if the work will take much longer than a day?

**Comment by iteles** [comment]
@MollieCourtenay Splitting this up and prioritising will be critical please as we currently only have 1 day allocated to this 👍

**Comment by MollieCourtenay** [comment]
@iteles @Cleop 
The above is in priority order - I don't have time today to split as i'm not with Mindwave today.
- menu needs to work and look better
- goals and strategies
- tracking showing the growth for problem tracker and diary for desktop and mobile as requested.

- caseload, messaging, details and contacts all smaller changes.

**Comment by Cleop** [comment]
@MollieCourtenay the Achieved Goals section will require new logic rather than just styling as currently all goals are listed as one. In the meantime I have been able to implement without consuming much time the ability to see the trophy (similarly to seeing the star for important) on goals that have been achieved so it's obvious that this is an achieved goal. However the other elements of the design will be more time consuming and I will break them down in issue #598 in more detail where I can put a specific time estimate on them.

This is the trophy:
![image](https://cloud.githubusercontent.com/assets/16775804/26253921/d5b5642a-3cac-11e7-84c6-279ee78d65f2.png)

**Comment by Cleop** [comment]
I'm going to break down this issue into smaller issues so we can track the changes that have been made.

**Comment by MollieCourtenay** [comment]
wonderful stuff
