### ISSUE TITLE
Carer tracking data /goals should not be displayed to the care team they're connected to

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#625]
+ [x] As a clinician, when I click on a carers name, I am taken to messages page by default. 
+ [x] As a clinician, when I click on a carers name, I can only see details and contacts / Messages - on the tabbed menu. 
+ [x] As a clinician, when I click on Details and contacts, I see a carers first and last name.

**Comment by katbow** [comment]
@MollieCourtenay Quick Qs about the details & contacts part of this

Since it's only name it's a bit bare

![image](https://cloud.githubusercontent.com/assets/1287388/26157923/5c0e858e-3b12-11e7-94a2-0b01b2c5ab7f.png)

There's nothing to remind the clinician that this is a carer & who they are caring for in this view. My suggestion is to include a general (carer) in the name at the top, and who they care for in the details & contacts view.

![image](https://cloud.githubusercontent.com/assets/1287388/26158610/4a6dc46e-3b14-11e7-8f89-38733a121eb7.png)

Instead of Name (carer) it could also say Name (friend/family/carer) if that's preferable wording.

**Comment by MollieCourtenay** [comment]
@katbow Thanks for this.
I knew it would be pretty empty  - but wanted to keep Details and contacts so Clinicians could begin to think about what else it would be useful to have in there.

For now please can you run with:

**Carer full name** (friend/family/carer) of **Service user full name**.

'cares for' also makes a presumption that there is a caring relationship - sometimes there isn't...

**Comment by katbow** [comment]
Sure thing. & is that only in the details & contacts section? Or across the top as well?

**Comment by MollieCourtenay** [comment]
@katbow  across the top as well would be great - if it is a quickie?

**Comment by Cleop** [comment]
@katbow I've changed (friend/family/carer) and the font weight of this in #650
