### ISSUE TITLE
Tracking: VIEW: custom symptom tracker - graph

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#626]
As a user I can see the data from my symptom tracker on a graph, so that I can look back and see how much/little i've been experiencing a symptom over time.

+ [x] a new item is added to the top of the Tacking overview graph key next to 'hours slept', it should display '[problem the user entered]' with a pink key item.
+ [x] the number from the scale 0-10 is added as a point on the graph on the day the data was saved
+ [x] the points on the graph should be pink
+ [x] if possible, pink lines connect the points on the graph

![clinician_tracking](https://cloud.githubusercontent.com/assets/25012688/26211104/8fb436b8-3be9-11e7-9811-e2a783ce30ff.png)

**Comment by MollieCourtenay** [comment]
Again forgive me If i am jumping in early again. But when a user has not entered a data point on the problem tracker. It shouldn't display as a 0. 
As 0 is a valid input -l it appears the user is not experiencing that problem at all - whereas, they've not saved any data.
