### ISSUE TITLE
Sleep tracker input page: add a few static sleep 'tips'

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#651]
As a user on Sleep tracker, I can see a set of sleep tips at the bottom of the page, so that I feel supported to get a better nights sleep.

+ [x] As a user, I see a grey box housing the sleep tips content at the bottom the the Sleep tracker page.
+ [x] As a user,  I see a centred and bold title 'Sleep tips' Same size as Sleep tracker title.
+ [x] As a user,  I see an intro sentence to the sleep tips in regular font.
+ [x] As a user, I see the sleep tracker icon, centred (just like diary input page)
+ [x] As a user, I see a set of sleep tips, the first statement in bold, the second in regular
+ [x] As a user, I see a gap between each tip.
+ [x] As a user, If I click on the links for Recovery College, progressive muscle relaxation, Sleep foundation, more tips - a new browser tab opens with that site.

## Content
https://docs.google.com/document/d/1SZEd5FudjuZxPge32PqGtuuLneu4o4xqKNS_E-0EjEc/edit

**Comment by iteles** [comment]
@MollieCourtenay Thanks for sharing the content!

Is there UI for this yet?

**Comment by MollieCourtenay** [comment]
👍
