### ISSUE TITLE
Tracking: styling changes

### ISSUE THREAD

**Issue by Cleop** [healthlocker/healthlocker#683]
As per #615 

# Clinician Tracking - 
![tracking view-01](https://cloud.githubusercontent.com/assets/25012688/26351387/5de35672-3faf-11e7-9f56-b1fb380a7718.png)
+ [x] 7 day average for Sleep = put in a blue 30% box
+ [x] each day put in a light grey box
+ [x] add the icon for each tracker that was completed for that day
+ [x] **Woke up** make bold 
+ [x] **Diary**- make bold 
+ [x] Indent the dairy timestamp
+ [x] add dark grey line separator between each tracker

![tracking_mobile](https://cloud.githubusercontent.com/assets/25012688/26242106/27546fb6-3c7f-11e7-9595-1aa07a92303d.png)

**Comment by Cleop** [comment]
@MollieCourtenay - I think these designs don't include the resized graph. Now that the graph is smaller, would you like the content boxes to match the full width of the container (as they and the graph used to) or would you like them to match the size of the graph in its new smaller format?

**Comment by MollieCourtenay** [comment]
@Cleop   the graph still looks bit to me so its hard to imagine - can you screenshot the options and add here so i can see what you mean?

**Comment by Cleop** [comment]
@MollieCourtenay of course:

![image](https://cloud.githubusercontent.com/assets/16775804/26360665/94fc120e-3fd0-11e7-9b10-5e20aba89bc3.png)

**Comment by MollieCourtenay** [comment]
Thanks @Cleop 
Could the 7 day average be graph width, and the grey box with day detail keep their wider width?
I think once diary is in there, the slimmer version would end up being very long.

**Comment by Cleop** [comment]
@MollieCourtenay, that's fine... the only other thing is that now the category icon looks weird in the middle: 
![image](https://cloud.githubusercontent.com/assets/16775804/26361933/69a36b08-3fd4-11e7-8927-2749c57915aa.png)

**Comment by MollieCourtenay** [comment]
@Cleop middle placement of icons is only for mobile screens.... The bigger screenshot above is desktop.

**Comment by iteles** [comment]
@MollieCourtenay @indiamindwave24  One more question on this. Adding the icon _above_ the entries on mobile could lead to quite a substantial amount of scrolling, particularly when there are 7 days worth of data for 3 trackers here.

Should we _try_ adding a small icon to the left or are you keen to test the icons above the text with users first?

**Comment by MollieCourtenay** [comment]
@iteles Happy for you to try a small icon on the left - appreciate the length! Thanks for checking in.
(this is why initially we wanted to be able to navigate day by day vs listing the whole week)

**Comment by MollieCourtenay** [comment]
@RobStallion @Cleop 
The dots are grey not pink now on my iphone 5s. safari.
![img_2466](https://cloud.githubusercontent.com/assets/25012688/26498677/ba838512-4227-11e7-8e6c-f81dc4b2af31.PNG)
