### ISSUE TITLE
Read recovery stories from other people

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#8]
As a person using HL,
I can read recovery stories from other people
so that I can feel inspired in my own journey.

Requires that other users can input their own content #5, and that it is displayed to other people.

<img src="https://cloud.githubusercontent.com/assets/1287388/22246319/2c620d04-e22c-11e6-9fa2-4776c8587740.jpg" width="200">

# Tasks:

- [x] Create UI for how information will be viewed

- [x] Accumulate stories from other users (#5)

- [x] Store & display stories from the database

## Acceptance Criteria

 _(covered in #10  Users should see a hero ‘recovery story’ at the top of the splash page.  AND Users should be able to see cards for a couple more recovery stories (under tip of the day and places to go cards on splash page)  )_

- [x] each recovery story card will display: title, first 30 words (up for discussion)
- [ ] user can click to see more ‘recovery stories’ and more cards are revealed at the bottom of the splash page
- [x] users can click to read the rest of the story - keep the user on HL but in a new page, not link out to external site.
- [x] A user can 'like' a recovery story
- [ ] at the end of the story, user is presented ‘you might also like’: and a couple more story cards are visible.

**Comment by katbow** [comment]
- [ ] Create UI for how information will be viewed

**Comment by nelsonic** [comment]
@katbow this is _our_ understanding of this story from the original User Story list.
@MollieCourtenay please _confirm_ the requirement and acceptance test 
and that we are ok to _proceed_ with working on it. thanks. 👍

**Comment by MollieCourtenay** [comment]
<img width="109" alt="screen shot 2017-01-29 at 22 15 02" src="https://cloud.githubusercontent.com/assets/25012688/22408422/692a262a-e670-11e6-9dac-c611935960af.png">


## Acceptance Criteria

 _(covered in #10  Users should see a hero ‘recovery story’ at the top of the splash page.  AND Users should be able to see cards for a couple more recovery stories (under tip of the day and places to go cards on splash page)  )_

[ ] each recovery story card will display: title, first 30 words (up for discussion)
[ ] user can click to see more ‘recovery stories’ and more cards are revealed at the bottom of the splash page
[ ] users can click to read the rest of the story - keep the user on HL but in a new page, not link out to external site.
[ ] at the end of the story, user is presented ‘you might also like’: and a couple more story cards are visible.


Recovery stories will in the same google sheet in tab 3:  https://docs.google.com/spreadsheets/d/197iLcKD6hJfx81KldY5GwBuU-4IEmFqPXvKAm9V9wLU/edit#gid=1496530273

**Comment by katbow** [comment]
At the moment, I formatted the cards to show a limited amount of content and the users can click to read the rest of a story. The second criteria is reliant on the splash page completion #10 so that will be completed as the splash page is built.

@MollieCourtenay for the last section of the acceptance criteria, can these be any other randomised recovery stories?

**Comment by LauraNevo** [comment]
>  user can click to see more ‘recovery stories’ and more cards are revealed at the bottom of the splash page

@MollieCourtenay I thought they would to another page with a list of recovery stories, as it's what you wanted for the other types of content?

**Comment by MollieCourtenay** [comment]
@LauraNevo @katbow 

> click to see more recovery stories

I'm not fussy. but if we don't have to load a new page just to reveal a couple more recovery story cards then to me that feels like a simpler and nicer UX?

**Comment by LauraNevo** [comment]
I'm confused. You specifically asked for this way to display stories on a
new page to keep it consistent with events.

I don't have a grasp on how much content there is for recovery stories so
if you think there aren't going to be many more, sure, we can display it on
the home page.

**Comment by LauraNevo** [comment]
Sorry, my message cut the end. I was going to say @MollieCourtenay we could define a number of items to be displayed on the home page and if it ever grows, we show a link to another page with all the stories. What do you think?

**Comment by LauraNevo** [comment]
Update on this (just added a Favourite button):

![recovery story](https://cloud.githubusercontent.com/assets/3858131/23085539/368d4e96-f560-11e6-882d-ba44f6bfa986.png)
