### ISSUE TITLE
Clinician connection flow

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#838]
We need to figure out how a clinician will sign up to HL and connect their HL account to ePJS data.

Current options are:
1. **Use a flow similar to that of a service user connecting HL to ePJS.**
* the clinician would sign up to HL as any other user would
* the clinician can then connect their account as a clinician i.e. have another link in account or as part of the sign up process
* the clinician enters `GP_Code`, `First_Name` and `Last_Name` and this is checked against the data in ePJS. (open to suggestions for other fields that can be used, but these seemed the most useful & least likely to change)
* if **all three** match, then the role is updated to clinician, and in a *new field* in HL `users` the `GP_Code` is added as a unique identifier.
* NB: once a clinician signs up & logs in once, they can remain logged in if they do not log out of HL/clear cookies. 

2. **Button in ePJS**
* a button exists in ePJS, which when clicked, generates a token
* the token signs up/logs in the clinician to HL, where the caseload will be available

**Questions**
1. What would we need to do from our side/what would need to be done externally for option 2?
2. Is there a general time estimate for how long option 2 would take? Option 1 estimate is ~T1d.
3. Are there any other ways to implement that I am missing that may be better options? 
4. Is there a preferred implementation from either of these 2 options or from any others that I have not thought of?

**Comment by katbow** [comment]
```
var Connection = require('tedious').Connection;
var Request = require('tedious').Request;


// Create connection to database
var config = {
  userName: 'ServerAdmin', // update me
  password: '4j5Q9Kzl43t8', // update me
  server: 'hl-test-server.database.windows.net', // update me
  options: {
      database: 'test', //update me
      encrypt: true
  }
}
var connection = new Connection(config);

// Attempt to connect and execute queries if connection goes through
connection.on('connect', function(err) {
    if (err) {
        console.log(err)
    }
    else{
        insertIntoDatabase()
    }
});

function queryDatabase(){
    console.log('Reading rows from the Table...');

    // Read all rows from table
    request = new Request(
        "SELECT pc.Name as CategoryName, p.name as ProductName FROM [SalesLT].[ProductCategory] pc JOIN [SalesLT].[Product] p ON pc.productcategoryid = p.productcategoryid",
        function(err, rowCount, rows) {
            console.log(rowCount + ' row(s) returned');
        }
    );

    request.on('row', function(columns) {
        columns.forEach(function(column) {
            console.log("%s\t%s", column.metadata.colName, column.value);
        });
    });

    connection.execSql(request);
}

function insertIntoDatabase(){
    console.log("Inserting a brand new product into database...");
    request = new Request(
      "INSERT INTO stuffs (Name) VALUES ('katbow')",
        // "INSERT INTO SalesLT.Product (Name, ProductNumber, Color, StandardCost, ListPrice, SellStartDate) OUTPUT INSERTED.ProductID VALUES ('OtherNewProduct', '300988', 'Green', 75, 80, '4/7/2016')",
        function(err, rowCount, rows) {
            console.log(rowCount + ' row(s) inserted');
        }
    );
    connection.execSql(request);
}
```

**Comment by katbow** [comment]
Update from the call with Mollie & Katy:
What previous conversations occurred between Nelson & Garry regarding the button/token it generates? If there are any gaps in what we need in order to implement the button, then we need to talk to Garry today to get this information (as he is off on Thursdays).

**Comment by katbow** [comment]
For option 2 as a general overview of what I think will need to be done for it along with some unknowns in the process, I think it would ~2 days.

General tasks:
* Check unique epjs identifier(example a `Staff_ID`) exists in ePJS data & check if clinician has logged in before
* Add data for clinician to HL db if they have never logged in before
* Create new log in route for clinicians which does not require the same data as other users: eg. doesn't require data access

**Comment by katyedwards** [comment]
Update from Garry:
They can use an http method to post the ‘username’ of the clinician logged into ePJS.

They have another integration between ePJS & a pathology system that employs this, so they can then re-use to do the same for HL.

He asks if someone would be able to go to work with him for a day this week (23rd) to get this set up - he is confident this can be set up (at least on the test database) in 1 day's work.

@katbow @nelsonic

**Comment by iteles** [comment]
@katyedwards We agree with that estimate. Let's book it in please 👍

**Comment by katyedwards** [comment]
Fab!

**Comment by nelsonic** [comment]
@katbow / @katyedwards after discussion with Garry, we concluded that simply having a `<button>` in ePJS was only _partially_ useful because people would not _know_ if/when they needed to click it to open HL ... so the (_already_) _busy_ NHS Staff would be clicking the button several times a day just to _check_ if there was any content (_updates from service users_) that required their attention.

Instead of just having a button we agreed 

I _implemented_ a (_super simplified_) version of this (_with a basic counter_) in March as a "_proof-of_concept_ using `node.js` code: https://github.com/dwyl/hits/blob/f4413d3bc7efdc9290ff0c917638a236bb865360/server.js#L24-L28

To implement this for HL we need:
+ [ ] Use cookies in the Healthlocker (Phoenix) App
+ [ ] Button in ePJS UI sources the image from Phoenix 
+ [ ] The handler checks cookie looks up user in DB and returns appropriate button based on number of notifications / messages for the clinician.

(_note this does not include Auth, but we can use our existing Auth Plug for checking the `cookie` to determine who the user is and return the appropriate number for the notification_)

Please let me know if you have any questions.

**Comment by nelsonic** [comment]
@katyedwards I don't there was ever a _suggestion_ (_or implication_) that we would _not_ be using authentication ... I'm trying to figure this out with Garry now... 🤔

**Comment by katyedwards** [comment]
Sorry - poorly worded, not *no authentication* but no *automated authentication*.  

We want to avoid the Clinicians having to sign up and enter data about themselves to then be authenticated as SUs do.  And then to have to manually login if their browser didn't remember them.

From the user research that seemed to be a real barrier.

**Comment by nelsonic** [comment]
OK, so this is the process that Garry & Team have defined (_and we are working towards_):

# "High Level Overview"

## Clinician Authenticates against Active Directory to get into ePJS 

+ Authentication is managed by ePJS and the clinician (or attacker) will need to have a valid/active account on the SLaM Active Directory (AD).

+ Once the valid AD user is validated then their account in ePJS is checked and if they have access to ePJS they are shown their ePJS dashboard.

### Notes on Authentication & Security

+ Security (authentication) is managed by SLaM's AD and ePJS. 
+ The Clinician does not register or login to Healthlocker.
+ Clinician clicks a Healthlocker button in ePJS and Healthlocker checks if the `userdata` (encrypted string) is valid (_see below_)
+ If `userdata` (_i.e. the clinician's ePJS Session is valid_) they are shown a caseload in Healthlocker

# Technical/Implementation Detail 

> FAO: @katbow & @RobStallion 

## A JavaScript Function in ePJS Gets the `UserName` & `UserId`

A JavaScript Function in ePJS's Front-end gets the `UserName` & `UserId` from the Clinician's ePJS Session and sends this data to MS SQL Server Stored Procedure (_see next step_) for encryption by `XMLHttpRequest` ("Ajax").


> Note: The JS Function is maintained by James/Garry in the SLaM team (_dwyl/mindwave do not have access/control to it, but I read the code and it looks fine_)

## MS SQL Server Stored Procedure Encrypts String

+ (A stored procedure on) MS SQL Server receives a `String` in the form of of:
```
UserName=garry@nhs.uk&UserId=ABCDE-6A7D-4A76-BA63-C3003787F63E&tokenexpiry=2017-06-23T11:15:53
```
And _encrypts_ it to:
```
'AQAAADyhSQUqcHkOWTRX80nd0Qfa7rO+x63hsOMqs2UzJd60kzxrYZb8C9Klf4SYQjX1BOV1WFXuDd2xXd36niOxuo67K8iyrnGqqeZgkGE6AOMTeGyHkoY7QoGAagl17DsXS07FhlY8iAIdD4lb2eAYMXd6tXsV4+HSjlJ0ufKL7lCU'
```

## Healthlocker Button in ePJS

In ePJS the Healthlocker button is hyperlinked to the `/caseload` endpoint in Healthlocker and includes a `userdata` url parameter:

```
https://www.healthlocker.uk/caseload?userdata=AQAAAFP2n1VCC67px77oys1Hwxi3evQ0UTK8x6rEmSiYYgeQ0gQ/SJ2fCOPp9PHaKJe7XTpcOIF5fBBEmYmvaXzPjigQMvJyPBxbDgBYMI36KcqMm4o/59VzLbaQIYkGIcwc+CycoinBkLOVK/d/zZt1peekgUs8JI/bHqdPaNo/Y1E3
```

## Clinician Clicks on Healthlocker Button in ePJS

When a clinician clicks on the Healthlocker Button in ePJS they are taken to the https://www.healthlocker.uk/caseload page ...
we have to interpret if the `url` has a `userdata` parameter and then _verify_ the Encrypted String

# Verifying the `userdata` (Encrypted String)

Inside the `/caseload` controller we need to verify the `userdata` if it is present in the url.

## Option 1: Call Stored Procedure in MS SQL

Our first option for decrypting the `userdata` is to use a stored procedure created by Garry
called `usp_DE_EncryptText` which accepts a string and returns the decrypted string:

```
exec usp_DE_EncryptText 'AQAAAKC7TOONooH/W/gavVibNRILDwIG+qpJTCOV9gbDnQLR+rcTuJiCHzOldtPl20G5Lyv4XS8iht0KIN/OPkag+56GcFlX0p+ieIrttGqxZok6dmjq/Tak1feDC/LIwtK3zt23+N8J2KJs/IY1G7HMsy7cF5tkDRPk/g=='
```
returns:
```
UserName=garry@nhs.uk&UserId=ABCDE-6A7D-4A76-BA63-C3003787F63E&tokenexpiry=2017-06-23T11:15:53
```

> **However**: our (_read-only_) user on the SQL Database does not _currently_ have _permissions_ to run stored procedures, so for now we are _stuck_ with "Option 2" (_see next_)

## Option 2: Run the Decryption Query as "Raw SQL" from HL/Elixir

Our second option is to run a chunk of SQL code to decrypt the string.
I have included the _actual_ code in `/home/hladmin/mssql_test/decrypt.js`:
![decrypt-js-sql-script-with-str-pwd](https://user-images.githubusercontent.com/194400/27484145-127c1b4a-5820-11e7-85a9-9fc2b04585e7.png)

To run the `decrypt.js` script:
```
ssh hladmin@51.140.86.5
cd mssql_test
node decrypt.js
```
e.g:
![node-decrypt-userdata](https://user-images.githubusercontent.com/194400/27483743-8386c63e-581e-11e7-855f-5b6f056e27ca.png)

We would need to run the SQL included in `decrypt.js` from within Healthlocker passing in `userdata` string.

> Note: we aren't going to be running the SQL Query to decrypt `userdata` as `JavaScript` in prod this is merely a _demonstration_ of it working ... we will need to run this from inside Healthlocker
and we will need to use environment variables for the `DECRYPTION_PASSWORD`;

## Lookup the Clinician's Caseload

Once we have _verified_ that the clinician/user is authorised to access Healthlocker (_by decrypting the `userdata` url parameter_) we would then use the `UserId` parameter in the _decrypted_ string to lookup their caseload in ePJS (_the MS SQL Database_).


@katbow / @RobStallion if everything is clear in this description, please leave a comment, otherwise ask questions. thanks!
I'm leaving Garry's office now and will be back in Mile End in a couple of hours

**Comment by katbow** [comment]
I think I understand everything.

From our perspective, once the clinicians clicks on the healthlocker button in ePJS, we need to:
* decrypt the UserData
* Ensure the UserID exists in epjs & if it does, use it to get caseload from the mhlTeamMembers table. (**question** is this field named the same in epjs?)
* If it doesn't exist, do something else (i.e. flash that they do not have access)

I also understand from this that clinicians will not exist in the HL database in any way. That's fine, but will have some implications for messaging that we will need to change (one I know for certain is that the first and last name in healthlocker are used in displaying messages, so if this doesn't exist there is an error). We will need to do a check on user type and get name accordingly.

**Comment by katbow** [comment]
We went through this together this morning and came across a few more things that need changing & some questions we had around that.

The caseload link is currently displayed if the healthlocker current_user has the role of clinician. Should we assign a current user for the clinician from epjs? This wouldn't need to be all the data from epjs.

We need to ensure the userData is passed to both the Room & User Controllers so we can authorise the clinician. We're not certain of the best way to do this. Can the `User_Guid` be stored as part of current user? Or should the full userData string be passed along as a param and decoded in the same way?

For messaging there are a few implications. One I mentioned above is getting the name from ePJS for clinicians. Another is that clinicians are currently added to a room by their HL `user_id`. We need to add different information here from ePJS in its place, such as the `User_Guid`. What will be acceptable for us to store in HL for this purpose?

**Comment by MollieCourtenay** [comment]
@katbow who are these questions aimed at? Do you need some input from us?

**Comment by nelsonic** [comment]
@katbow hopefully our discussion with diagram clarified the process this morning.
To re-cap:
+ Add `guid` column to the [`user`](https://github.com/healthlocker/healthlocker/blob/master/web/models/user.ex) model.
+ If the person clicks the HL Button/Link in ePJS and they have a `userdata` parameter in the URL we decrypt it using the SQL Query (_as described above_)
+ `if` the `guid` ***is*** in the `users` table of the HL database ***login()*** the user as a HL user so that all other functionality works as expected. 
+ `else` the `guid` is ***not*** in the `users` table ***register()*** the Clinician as an HL user with a _random_ string as their password (_so their account is protected and they can `reset` it at a later time if they **choose** to access HL **directly**_)

@katbow / @RobStallion please _confirm_ this is OK. thanks. 👍

**Comment by iteles** [comment]
@MollieCourtenay These were for @nelsonic, sorry for the confusion
 👍
