### ISSUE TITLE
Azure Staging Server Deployment (DevOps Setup)

### ISSUE THREAD

**Issue by nelsonic** [healthlocker/healthlocker#841]
As part of the migration/deployment to SLaM's (Azure) Infrastructure
Stuart has provisioned a "Staging" Server. 

## TODO
+ [ ] Install all necessary Dependencies as per: [production-deployment.md](https://github.com/dwyl/learn-phoenix-framework/blob/master/production-deployment.md)
  + [ ] Erlang
  + [ ] PostgreSQL
  + [ ] Build tools
+ [ ] Manually Test Deployment from `localhost` to `staging`
+ [ ] Setup subdomain: http://staging.healthlocker.uk
+ [ ] Setup Travis Continuous Delivery to deploy any merged PR to staging
+ [ ] Document all steps with detailed instructions and screenshots
+ [ ] Request peer-review
+ [ ] Request Product Owner Feedback (testing the app on staging.healthlocker.uk

> **Note**: These tasks _should_ not take `T1d` but I'm budgeting for:
+ unforeseen delays due to permissions/configuration issues
+ _completely_ documenting each step in the process so it can be replicated (owned) by SLaM

**Comment by nelsonic** [comment]
Subdomain: 
![image](https://user-images.githubusercontent.com/194400/27381567-36c4935c-567b-11e7-9443-487a62da912d.png)

**Comment by nelsonic** [comment]
Subdomain working: http://staging.healthlocker.uk/
![image](https://user-images.githubusercontent.com/194400/27381985-cd37c934-567c-11e7-8390-d4ddd5dd5584.png)

> NOTE: not yet ready for UAT! 👍

**Comment by nelsonic** [comment]
Added Environment variables to `~/.profile`

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/27387091-a6eeb9fa-568f-11e7-8e26-beb6dc7e1c40.png)

**Comment by nelsonic** [comment]
Trying to run:
```
sudo MIX_ENV=prod mix phoenix.server
```
Getting error: 
```
** (Mix) Cannot execute task because the project was not yet compiled. When build_embedded is set to true, "MIX_ENV=prod mix compile" must be explicitly executed
```
Even though I have _just_ compiled ...
![image](https://user-images.githubusercontent.com/194400/27390219-a99fd18a-5698-11e7-8a78-e84178610543.png)

**Comment by nelsonic** [comment]
Why does the app still think it's connecting to a "Read Only" PostgreSQL ...?
![image](https://user-images.githubusercontent.com/194400/27390760-060ce2ea-569a-11e7-9986-ea49909becfb.png)

@katbow is this because the code to switch out from the `Healthlocker.ReadOnlyRepo` to MSSQL is still on a branch?

**Comment by RobStallion** [comment]
@nelsonic currently we have only configured the app for dev environment and those changes are on the branch [mssql-setup](https://github.com/healthlocker/healthlocker/tree/mssql-setup)

**Comment by nelsonic** [comment]
@RobStallion yeah, I noticed. thanks.
We need to get those changes into `master` soon so we can finish the deployment. 👍 
thanks!

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/27630902-c196b974-5bee-11e7-83a1-b9134e2ed026.png)

Tried to run:
```
MIX_ENV=prod mix phoenix.server
```
got: 
![image](https://user-images.githubusercontent.com/194400/27631340-0fd08d3a-5bf0-11e7-87c9-c35da9b85842.png)

**Comment by nelsonic** [comment]
Still getting:
![image](https://user-images.githubusercontent.com/194400/27633400-f186c3ce-5bf6-11e7-890c-b682e3f792a4.png)
Think we need to remove [`ssl: true`](https://github.com/healthlocker/healthlocker/blob/0075b1e0662228fdd7d8e63aff74f338f712e6cb/config/prod.exs#L34)

**Comment by RobStallion** [comment]
Ok will do now

**Comment by nelsonic** [comment]
Git pulled the latest `config/prod.exs` and built release:
![image](https://user-images.githubusercontent.com/194400/27634961-42531900-5bfd-11e7-99a9-6df99ad199d9.png)

Attempting to deploy:
![image](https://user-images.githubusercontent.com/194400/27635007-6e3b6a4a-5bfd-11e7-9dac-8bc224e63841.png)

Now reading the logs on the `staging` server...

**Comment by nelsonic** [comment]
http://staging.healthlocker.uk/ or http://51.140.86.5/ gives `503`:
![image](https://user-images.githubusercontent.com/194400/27635067-9b3910ec-5bfd-11e7-8759-24de08fe1e24.png)

**Comment by nelsonic** [comment]
I'm checking the logs to see why we're getting a `503`.
for anyone `else` following along, this is how: https://stackoverflow.com/questions/43996349/how-to-view-production-logs-in-phoenix-web-application-deployed-using-edeliver

**Comment by nelsonic** [comment]
When "ssh-ed" into the `staging` server the logs for the app deployed using `edeliver` are in `/home/hladmin/healthlocker/var/log`:
![image](https://user-images.githubusercontent.com/194400/27635224-14ed70cc-5bfe-11e7-8d4f-c6773bc3e8f2.png)

Running the following command will show the logs in reverse chronological order (_most recent first_):
```
ls -lath
```

**Comment by nelsonic** [comment]
@RobStallion / @katbow any reason we have so many _duplicate_ firewall ("ip tables") rules:
![image](https://user-images.githubusercontent.com/194400/27635417-d4dc52f4-5bfe-11e7-99c4-17cbadf31dc6.png)

I have removed the duplicates now... please ensure you _understand_ the command you are running `before` executing it. 😉

**Comment by RobStallion** [comment]
I noticed that a little earlier when we were going through your [readme](https://github.com/dwyl/learn-microsoft-azure#redirect-tcp-port-80-to-port-4000-where-our-app-is-listening) but wasn't sure how to remove the duplicates 😞 .

**Comment by nelsonic** [comment]
on my `localhost` I'm running:
```
mix edeliver build release --verbose
```
to get as much feedback on the build process as possible.

**Comment by nelsonic** [comment]
Based on the updated `prod.exs` see: https://github.com/healthlocker/healthlocker/pull/876
I'm no re-running the deployment script: `mix edeliver build release --verbose`

**Comment by nelsonic** [comment]
`edeliver` reports that the deployment "worked":
![image](https://user-images.githubusercontent.com/194400/27636997-f291f43c-5c05-11e7-86fd-fbc3e30eb81c.png)

But visiting http://51.140.86.5/ still shows a blank screen. 😞 
Reading logs now ...

**Comment by nelsonic** [comment]
Stopped the app:
```
mix edeliver stop production
```
> note: until we _have_ a "production" environment we are deploying "production" to the `staging` server ... (_apologies if there's confusion, we only have one server!!!_)

![image](https://user-images.githubusercontent.com/194400/27637233-f16a932e-5c06-11e7-9b89-44df475cf7d0.png)

I'm _unsure_ if the Port forwarding is working ... 🤔 
I'm going to _delete_ all Firewall rules on the `staging` server,
and attempt to run NGINX on port 80 following _these_ instructions: https://github.com/dwyl/learn-microsoft-azure#12-install--run-nginx-to-test

**Comment by nelsonic** [comment]
Started NGINX:
![image](https://user-images.githubusercontent.com/194400/27637438-9f94b916-5c07-11e7-82e4-4a6da02e4666.png)
Still getting 503:
![image](https://user-images.githubusercontent.com/194400/27637460-b3cdc508-5c07-11e7-8522-5d7b62157cdf.png)

this is _non-sensical_!

**Comment by nelsonic** [comment]
Ok. I created the file: `/etc/nginx/sites-enabled/default.conf` with a single line of config:
```
server { listen 80; }
```
> based on the answer on SO: https://stackoverflow.com/a/12800469/1148249

then re-started nginx:
```
sudo service nginx restart
```
And got:
![image](https://user-images.githubusercontent.com/194400/27637723-a0780094-5c08-11e7-862c-510877d646d2.png)

`#progress` (_but I'm not counting my chickens ..._)

**Comment by nelsonic** [comment]
Now I'm going to try and configure `nginx` to proxy the phoenix app with the following `default.config`:
```
server {
    listen 80;
    server_name staging.healthlocker.uk;
    location / {
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   Host      $http_host;
        proxy_pass         http://127.0.0.1:4000;
    }
}
```

believe it or not this is progress:
![image](https://user-images.githubusercontent.com/194400/27637942-6cad3e0e-5c09-11e7-9030-fdbeb0cc03f6.png)

**Comment by nelsonic** [comment]
Found this `nginx.conf` file: https://gist.github.com/micho/1712812 for proxying TCP Port `80` to `3000` seeing how much of it we need ...

**Comment by nelsonic** [comment]
Tried updating `/etc/nginx/sites-enabled/default.config` to:
```
server {
  listen       80;
  server_name  localhost;
  location / {
    proxy_pass          http://localhost:4000;
    proxy_set_header    Host             $host;
    proxy_set_header    X-Real-IP        $remote_addr;
    proxy_set_header    X-Forwarded-For  $proxy_add_x_forwarded_for;
    proxy_set_header    X-Client-Verify  SUCCESS;
    proxy_read_timeout 1800;
    proxy_connect_timeout 1800;
  }
}
```
Got:
![image](https://user-images.githubusercontent.com/194400/27638313-b63dfe68-5c0a-11e7-8df7-0c3aa94cdb35.png)

Reading: https://dennisreimann.de/articles/phoenix-nginx-config.html

**Comment by nelsonic** [comment]
seems pretty obvious, but confirm that phoenix app is running on port 4000 ...
![image](https://user-images.githubusercontent.com/194400/27638534-7e7b9b6a-5c0b-11e7-8ed3-4eb5525a443a.png)
and it's not!!
checking logs:
```
cd /home/hladmin/healthlocker/var/log
ls -lath
tail erlang.log.1 -n 100
```

![image](https://user-images.githubusercontent.com/194400/27638722-11a1d224-5c0c-11e7-90fd-2966cabac187.png)

So... something/someone changed the PORT that our app is running on so it's no longer using TCP 4000!! 😭 
we can _investigate_ this further once the site us up-and-running again but for now,
I'm setting `export PORT=80` in `/home/hladmin/.profile`

**Comment by nelsonic** [comment]
@RobStallion & @katbow deployment with `edeliver` is not working as expected.
this is ***100%*** a configuration issue.
however, _manually_ running `mix phoenix.server` on the `staging` server works:
```
sudo -i
cd /home/hladmin/hl-app
mix phoenix.server
```
then visit: http://staging.healthlocker.uk/ or http://51.140.86.5/ and you should see:
![image](https://user-images.githubusercontent.com/194400/27639200-6871c6ee-5c0d-11e7-991b-c2d641dc7ca8.png)

Please _confirm_ you are able to replicate this. (_thanks!_)

**Comment by RobStallion** [comment]
Have replicated the step above and have it working 

![image](https://user-images.githubusercontent.com/15571853/27640168-64a2030a-5c10-11e7-90d6-98d131fee049.png)

**Comment by nelsonic** [comment]
@RobStallion thanks for confirming you can replicate steps to start app on `staging` (_manually_)
I'm attempting to deploy using `edeliver` are you guys using `staging` server right now? 🤔

**Comment by katbow** [comment]
@nelsonic no, neither of us is using the staging server right now

**Comment by nelsonic** [comment]
When attempting to deploy to staging using `edeliver`, I think the _reason_ that it's not running is that the dependencies were installed as `root` but we are deploying using `hladmin` i.e. a lower privilege user so we don't have _access_ to the dependencies! 😢 

however when I _attempt_ to deploy using `root` in the `.deliver/config` I get: 
```
Please login as the user "hladmin" rather than the user "root".
```

@RobStallion could you please _confirm_ that _everything_ you installed on `staging` to get the server working with the _manual_ start (`mix phoenix.server`) is listed in the `Vagrantfile`? (_thanks_!)

**Comment by RobStallion** [comment]
@nelsonic As far as I am aware that is the case. I have been wanting to check and confirm but due to the work that you have been doing on the staging server I felt it was best not to tamper with it at this point in time. Just wanted to give an update.

**Comment by nelsonic** [comment]
Hi @RobStallion!
If you need to ***manually*** deploy the **master** branch to the healthlocker server you will need to perform the following ***11 steps***:

+ [ ] login to the server using **ssh hladmin@ip-address
+ [ ] copy your _public_ ssh key from **/home/hladmin/authorized_keys**
+ [ ] type: **su -i**
+ [ ] paste your _public_ ssh key on a new line in **/home/root/authorized_keys** (_and **save** the file_)
+ [ ] type: **exit** (_twice to exit the ssh session_)
+ [ ] now test logging into the server as **root** with the following command: **ssh root@ip-address** .. if that worked ur almost there! Let me know if not!
+ [ ] now use **edeliver** to build and deploy the latest version:
  + [ ] git checkout master && git pull
  + [ ] mix edeliver build release --verbose
  + [ ] mix edeliver stop production
  + [ ] mix edeliver deploy release to production
  + it should ask you for the version, type the latest version number into your terminal.
  + [ ] mix edeliver start production

Please let me know how you get on.
If you get stuck please comment with as _much_ detail as possible: 
+ any error messages (as text)
+ screenshots of errors

Thanks!

**Comment by RobStallion** [comment]
commands I have run

- ssh hladmin@ip-address
- /home/hladmin/.ssh/authorized_keys
- sudo -i
- paste your public ssh key on a new line in /root/.ssh/authorized_keys (and save the file)
- type: exit (twice to exit the ssh session)
- logged into the server as root with the following command: ssh root@ip-address ..
- cd /home/hladmin/hl-app/
- git checkout master && git pull origin master
- mix edeliver build release --verbose

Got the following error at this stage...
```
A remote command failed on:

  hladmin@ip-address

Output of the command is shown above and the command executed
on that host is printed below for debugging purposes:

FAILED with exit status 255:

    set -e
    if [ ! -d /home/hladmin/healthlocker/builds ]
    then
      mkdir -p /home/hladmin/healthlocker/builds
      cd /home/hladmin/healthlocker/builds
      git init
      git config receive.denyCurrentBranch ignore
    else
      cd /home/hladmin/healthlocker/builds
      git config receive.denyCurrentBranch ignore
    fi
```

**Comment by katbow** [comment]
I ran the exact same steps as @RobStallion and had the same error.

**Comment by nelsonic** [comment]
You need to deploy from **localhost** not the server.
I tried to updat my comment above, but each time I tried, GitHub rejected my updated. 😢

Deploy from **localhost** (_i.e: **not** ssh-ed into the staging server...)
You tested **ssh root@ip-address** to _confirm_ that **edeliver** has access to the **staging** server.

**Comment by RobStallion** [comment]
Following on from commands I have run above

- logged into the server as root with the following command: ssh root@ip-address ..
- That worked so typed exit to go back to my local terminal
- git checkout master && git pull
- mix edeliver build release --verbose

Got the same error when running the last command in my local terminal...

![image](https://user-images.githubusercontent.com/15571853/27877877-447f29a0-61b4-11e7-9d85-9c326ba3d5bc.png)

updated the `BUILD_USER` and `PRODUCTION_USER` variables in the `.deliver/config` file to say `"root"`

running commands again

- mix edeliver build release --verbose
  + got the following warning during build
![image](https://user-images.githubusercontent.com/15571853/27878503-53cebb6c-61b6-11e7-8e68-76bf3c291042.png)

![image](https://user-images.githubusercontent.com/15571853/27878041-cd14d616-61b4-11e7-9a35-d1fe8b981324.png)
- mix edeliver stop production
  + staging site has gone down.
- mix edeliver deploy release to production
  + didn't ask for the version 
- mix edeliver start production

![image](https://user-images.githubusercontent.com/15571853/27878269-86cf9ef6-61b5-11e7-9cf8-72ee4372da75.png)

Seems to have deployed correctly and site is back up and running now.

**Comment by nelsonic** [comment]
running:
```
mix edeliver version
```
we see:
![image](https://user-images.githubusercontent.com/194400/28167700-64e959ec-67d4-11e7-9821-e51bed0cead9.png)

adding `STAGING_HOSTS` config now. ⌛️

**Comment by nelsonic** [comment]
Attempting to do Auto-Versioning for release precision:
https://github.com/edeliver/edeliver/wiki/Auto-Versioning

for some reason the release is not on the build (`staging`) server:
![image](https://user-images.githubusercontent.com/194400/28191282-3e7f9cd2-6827-11e7-9c15-ad6c69331dc4.png)

**Comment by nelsonic** [comment]
build initial release:
```
mix edeliver build release --verbose
```
that worked fine.

then I attempt to run an "upgrade" command:
```
mix edeliver upgrade staging --verbose --auto-version=revision
```
but still get error:
```
==> Upgrading healthlocker from 1.0.2 to 1.0.3+dd96a13
==> Upgrade failed, version 1.0.2 does not exist:
    expected at: _build/prod/rel/healthlocker/releases/1.0.2
```

Continuing to investigate ...

**Comment by RobStallion** [comment]
We are currently having an [issue with sending messages](https://github.com/healthlocker/healthlocker/issues/915). It appears to be an issue with when the side is deployed using edeliver. 

@nelsonic do you have any leads on what could be causing this. If not I would like to look at the logs created during the edeliver build to see if they might have any clues on what could be going wrong. Would that be alright to do or are you still working on that side of things?

**Comment by reddog** [comment]
@nelsonic @RobStallion Is this due to a mis-configuration with nginx for websockets?

See:
http://www.phoenixframework.org/docs/advanced-deployment#section-setting-up-our-web-server
https://stackoverflow.com/questions/38229629/how-to-set-up-websockets-with-phoenix-behind-nginx

**Comment by nelsonic** [comment]
@reddog yes, the NGINX proxy pass for WebSockets needs to be configured.

**Comment by reddog** [comment]
@nelsonic Thanks for the update.  I have tried with a test service user but it still failed:

![image](https://user-images.githubusercontent.com/151362/28415046-fe0c04a0-6d45-11e7-92bc-65057576b0c9.png)

`app.js:1 WebSocket connection to 'wss://staging.healthlocker.uk/socket/websocket?token=SFMyNTY.g3QAAAACZAAEZG…c2lnbmVkbgYAxxK6X10B.bHoL6JSDGf58SX4D9_sp8VLWtmHNaY15s4qDStZgjTQ&vsn=1.0.0' failed: Error during WebSocket handshake: Unexpected response code: 403`

I'll forward the test service user details by Slack

**Comment by nelsonic** [comment]
@reddog still debugging it. the configuration has been set to proxy-pass WebSockets since last week when it was deployed, and there are no errors in the NGINX logs so trying to figure out why ...

**Comment by reddog** [comment]
@nelsonic what are the contents of the current nginx configuration file?

**Comment by nelsonic** [comment]
@reddog _current_ NGINX config file: https://github.com/healthlocker/healthlocker/pull/936/files#diff-1ac1daaa31404162e1787cc7e6a31058

**Comment by reddog** [comment]
@nelsonic Thanks for the nginx config file link.

Saw your comment in #387.  Does that mean that websockets have been a long-standing issue?  Possibly the nginx config needing fixing anyhow, but maybe there was/is still an underlying websockets issue?

Has this ever worked from a non-nginx install?  Heroku?

**Comment by nelsonic** [comment]
@reddog messaging worked flawlessly on Heroku. 
I've updated the nginx config.
the line that fixed it was: 
```
proxy_set_header Origin '';
```
this was not documented _anywhere_ (on NGINX, WebSocket spec or Phoenix Docs) 
it was pure "_forensic googling_"

**Comment by reddog** [comment]
@nelsonic Thanks very much for that.

I don't know if this is root cause, but there are some (very few) comments on this on the Phoenix GitHub issues - the socket can be configured to turn off origin checking and/or the origin can be set (which I guess should then also be set in nginx config, not empty).  See https://github.com/dwyl/learn-phoenix-framework/issues/99#issuecomment-316768858

**Comment by nelsonic** [comment]
NGINX is now proxying the Phoenix app _including_ WebSockets #915  👍

**Comment by nelsonic** [comment]
@reddog the Azure deployment is working as expected.
The only thing that I want _add_ before considering this issue "_complete_" 
is to "***automate***" the deployment to `staging` from CI 
(_i.e. to have Continuous Delivery to a Staging ("test") environment_)

**Comment by reddog** [comment]
@nelsonic Thanks for the update.

Will you be competing the Continuous Deployment piece as part of the original Heorku -> Azure migration work?  And if so, when?

**Comment by reddog** [comment]
@nelsonic Thanks for the *reaction* reply.  Could you confirm:

1.  this remaining task will be completed as part of the Azure migration?
2.  will it will be completed?

**Comment by reddog** [comment]
@nelsonic Are you able to provide an update on previous queries about if and when the remaining tasks in this issue will be resolved?

**Comment by iteles** [comment]
@reddog Apologies I didn't see this earlier, as you know, we have been out of the office. 

To be clear, this isn't part of the original scope of the azure migration and will not have an impact for SLaM or the project. However, Nelson would like to ensure this is done for completion as an open source contribution and to facilitate the process for future developers.

**Comment by reddog** [comment]
@iteles Thanks for your reply.  I appreciate that you've been working remotely hence asking for when this would (ie maybe not right now) be completed.

I'm not 100% on your clarification of *isn't part of the original scope* and *Nelson would like to ensure this is done*.  Can you confirm if that means @nelsonic will be doing this (as if it were part of the original scope) and when, or if it would have to be completed as a separate item.

**Comment by reddog** [comment]
@markwilliamfirth This is down under Sprint 15 . Will it be completed during this sprint?

**Comment by markwilliamfirth** [comment]
@reddog sadly Nelson doesn't have availability to do this during this sprint - are the remaining checkboxes on the top issue things you would like @RobStallion and @katbow to do? I should note that the remaining checkboxes are not part of the original scope for sprint 14 and they are not currently part of sprint 15
