### ISSUE TITLE
Coping strategies for all users

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#88]
As an end user, I can set coping strategies, so that I have access to prompts for actions that I know will help me stay well if my behaviour, thoughts or mood change.

## Acceptance Criteria

+ [x]  As a user I can see 3 coping strategies when I click on 'Toolkit'
+ [x]  As a user if I have more than 3, I can click to 'See more' coping strategies
+ [x]  As a user I can create a new coping strategy
+ [x]  As a user looking at my coping strategies, the Add new button is available on the coping strategies landing screen. (currently there when viewing a coping strategy)

+ [x]  As a user I can click to view a single coping strategy
+ [x] I can edit a coping strategy when viewing a single coping strategy I have written myself
+ [x] I can delete a coping strategy when viewing a single coping strategy I have written myself

## Wireframes

![write edit coping strategies](https://cloud.githubusercontent.com/assets/3858131/22545410/8f115a80-e930-11e6-964c-36c6b1a64fec.png)

## Tasks

+ [x] Update schema to include association
+ [x] Update model/controller to handle inserting coping strategies into the db
+ [x] Update model/controller to handle getting coping strategies from the db
+ [x] Create page for displaying coping strategies (and later goals as well) - possibly users index?
+ [x] Create page for displaying single coping strategy where the user can add it to the get support screen, or delete the coping strategy.
#46 #37

**Comment by MollieCourtenay** [comment]
##COPY

**To view a coping strategy:**

Coping strategy displayed in bold text.
Created <XX/XX/XX>

[ ? ] Display on Get support screen

**To add a new coping strategy:**

Note down an action you can take to stay well.
Something can you do, or avoid doing when you notice a change in your feelings, thoughts or behaviour.
For example, practice relaxation techniques, leave the room if things are too tense, take a break or tell someone you trust.

[ ] Display on Get support screen

(Save)

**To edit a coping strategy:**

Note down an action you can take to stay well.
Something can you do, or avoid doing when you notice a change in your feelings, thoughts or behaviour.
For example, practice relaxation techniques, leave the room if things are too tense, take a break or tell someone you trust.

[ ] Display on Get support screen

(Save)

**Comment by katbow** [comment]
@MollieCourtenay for the non-SLaM users, would they be the only person adding coping strategies for themselves? e.g. can a carer or anyone else add a coping strategy for another user?

**Comment by MollieCourtenay** [comment]
@katbow not during this phase of the project perhaps an option in the future..

**Comment by katbow** [comment]
@MollieCourtenay I noticed there's no 'See all' under coping strategies on the toolkit view. Are all of the coping strategies supposed to be displayed here, or is it still limited to 3 and the button was just missed in the wireframes?

**Comment by LauraNevo** [comment]
@katbow Yes, it's a mistake on the wireframes, there are not updated. The acceptance criteria are the right to follow. I'm working on an updated version. :)

**Comment by LauraNevo** [comment]
Update on this, we decided to separate the Toolkit page (too much content to branch from there to keep in the same page):

![coping strategies](https://cloud.githubusercontent.com/assets/3858131/23085354/342c8a8c-f55f-11e6-8600-a37fdc757467.png)

**Comment by MollieCourtenay** [comment]
Similar changes needed here as with goals.

**Comment by MollieCourtenay** [comment]
Am closing having moved existing / new ACs into new issues.
